import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CircleAlert, Clock3, FileKey2, GitCommitHorizontal, GitPullRequest, History, Layers3, ReceiptText } from "lucide-react";

import { CopyEvidenceButton } from "@/components/console/copy-evidence-button";
import { DownloadEvidenceButton } from "@/components/console/download-evidence-button";
import { RunControls } from "@/components/console/run-controls";
import { RunJourney } from "@/components/console/run-journey";
import { ScheduleReviewControl } from "@/components/console/review-schedule-controls";
import { ReviewInterventionControls } from "@/components/console/review-intervention-controls";
import { StatusBadge } from "@/components/console/status-badge";
import { TabStateRouter } from "@/components/console/tab-state-router";
import { getReviewEvidenceData, getReviewInterventionData, type ReviewEvidence } from "@/lib/control-api";
import { formatTime, shortSHA } from "@/lib/format";
import { providerFileTarget, providerReviewTarget } from "@/lib/provider-review-url";
import { cn } from "@/lib/utils";

type TaskTab = "overview" | "evidence" | "logs" | "findings" | "timeline";
const tabs: { key: TaskTab; label: string }[] = [{ key: "overview", label: "Overview" }, { key: "evidence", label: "Evidence" }, { key: "logs", label: "Logs" }, { key: "findings", label: "Findings" }, { key: "timeline", label: "Timeline" }];

export default async function TaskDetailPage({ params, searchParams }: { params: Promise<{ org: string; taskId: string }>; searchParams: Promise<{ tab?: string }> }) {
  const [{ org, taskId }, query] = await Promise.all([params, searchParams]);
  const [data, interventionData] = await Promise.all([getReviewEvidenceData(org, taskId), getReviewInterventionData(org, { runID: taskId, limit: 1 })]);
  const evidence = data.evidence;
  const tab = tabs.some((item) => item.key === query.tab) ? (query.tab as TaskTab) : "overview";

  if (!evidence) return <div className="space-y-6"><Back org={org} /><section className="grid min-h-[420px] place-items-center rounded-[18px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-8 text-center"><div><CircleAlert className="mx-auto size-7 text-[var(--ls-text-tertiary)]" /><h1 className="mt-4 text-lg font-semibold text-[var(--ls-text)]">This review run is unavailable</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[var(--ls-text-secondary)]">{data.detail ?? "It may have been removed or be outside this workspace."}</p></div></section></div>;

  const run = evidence.run;
  const intervention = interventionData.interventions[0];
  const provider = providerReviewTarget(run);
  const duration = run.finished_at ? `${Math.max(0, Math.round((new Date(run.finished_at).getTime() - new Date(run.started_at ?? run.created_at).getTime()) / 1000))}s` : "In progress";
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Back org={org} /><span className={cn("inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs", data.source === "live" ? "bg-emerald-500/10 text-[var(--ls-success-text)]" : "bg-amber-500/10 text-[var(--ls-warning-text)]")}><span className="size-1.5 rounded-full bg-current" />{data.source === "live" ? "Immutable live evidence" : data.source.replaceAll("_", " ")}</span></div>
    <header className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_auto] xl:items-end"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge state={run.state} /><span className="rounded-full bg-[var(--ls-surface-muted)] px-2.5 py-1 font-mono text-xs text-[var(--ls-text-secondary)]">r{run.revision}</span></div><div className="mt-4 flex items-start gap-3"><GitPullRequest className="mt-1 size-5 shrink-0 text-[var(--ls-accent)]" /><div><h1 className="text-[32px] font-semibold leading-[38px] tracking-[-0.045em] text-[var(--ls-text)]">{run.title || `${run.repository} #${run.review_number}`}</h1><p className="mt-1 text-xs text-[var(--ls-text-tertiary)]">{run.repository} #{run.review_number}{run.author ? ` · opened by ${run.author}` : ""}</p><p className="mt-2 text-sm leading-6 text-[var(--ls-text-secondary)]">Exact head <span className="font-mono text-[var(--ls-text)]">{shortSHA(run.head_sha)}</span> · {run.trigger_kind.replaceAll("_", " ")} · {duration}.</p></div></div></div><div className="flex flex-wrap items-start gap-2"><DownloadEvidenceButton fileName={`open-review-${run.id}.json`} value={JSON.stringify(evidence, null, 2)} />{provider ? <a className="luminous-focus inline-flex h-10 items-center gap-2 rounded-[10px] bg-[var(--ls-accent)] px-4 text-sm font-medium text-white" href={provider.url} rel="noreferrer" target="_blank">Open {provider.label}<ArrowUpRight className="size-4" /></a> : null}<ScheduleReviewControl enabled={data.source === "live"} org={org} runID={run.id} state={run.state} /><RunControls acknowledgementRecoveryAvailable={evidence.acknowledgement_recovery_available} enabled={data.source === "live"} org={org} revision={run.revision} runID={run.id} state={run.state} /><ReviewInterventionControls enabled={data.source === "live" && interventionData.source === "live"} intervention={intervention} org={org} runID={run.id} /></div></header>
    <TabStateRouter className="flex gap-1 overflow-x-auto border-b border-[var(--ls-line)]" label="Run detail views">{tabs.map((item) => <TaskTabLink count={item.key === "findings" ? evidence.findings.length : item.key === "timeline" ? evidence.events.length : undefined} href={`/${org}/tasks/${run.id}?tab=${item.key}`} key={item.key} label={item.label} selected={item.key === tab} />)}</TabStateRouter>
    {tab === "overview" ? <Overview evidence={evidence} org={org} source={data.source} /> : null}
    {tab === "evidence" ? <Evidence evidence={evidence} hasRuleSnapshot={Boolean(data.ruleSnapshot)} /> : null}
    {tab === "logs" ? <Logs evidence={evidence} /> : null}
    {tab === "findings" ? <Findings evidence={evidence} /> : null}
    {tab === "timeline" ? <Timeline evidence={evidence} /> : null}
  </div>;
}

function Overview({ evidence, org, source }: { evidence: ReviewEvidence; org: string; source: string }) { const run = evidence.run; return <div className="space-y-5"><RunJourney initialEvents={evidence.events} initialRevision={run.revision} initialState={run.state} key={`${run.id}:${source}`} org={org} runID={run.id} streamEnabled={source === "live"} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={GitCommitHorizontal} label="Head revision" value={shortSHA(run.head_sha)} mono /><Metric icon={GitCommitHorizontal} label="Base revision" value={shortSHA(run.base_sha)} mono /><Metric icon={Layers3} label="Stages" value={`${evidence.stages.filter((item) => item.state === "succeeded" || item.state === "skipped").length}/${evidence.stages.length}`} /><Metric icon={Clock3} label="Started" value={formatTime(run.started_at ?? run.created_at)} /></div><section className="rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><h2 className="text-base font-semibold text-[var(--ls-text)]">Execution stages</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{evidence.stages.length ? evidence.stages.map((stage) => <div className="rounded-[12px] bg-[var(--ls-surface-muted)] p-4" key={stage.id}><div className="flex items-center justify-between"><span className="text-sm font-medium capitalize text-[var(--ls-text)]">{stage.stage}</span><span className={cn("size-2 rounded-full", stage.state === "succeeded" ? "bg-[var(--ls-success)]" : stage.state === "failed" ? "bg-[var(--ls-critical)]" : stage.state === "running" ? "bg-[var(--ls-accent)]" : "bg-[var(--ls-text-tertiary)]")} /></div><p className="mt-2 text-xs capitalize text-[var(--ls-text-secondary)]">{stage.state} · attempt {stage.attempt + 1}</p></div>) : <Empty title="No stage evidence" detail="Stage state has not been retained for this run." />}</div></section></div>; }

function Evidence({ evidence, hasRuleSnapshot }: { evidence: ReviewEvidence; hasRuleSnapshot: boolean }) { return <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><div className="flex items-center gap-2"><FileKey2 className="size-4 text-[var(--ls-accent)]" /><h2 className="font-semibold text-[var(--ls-text)]">Pinned snapshots</h2></div><div className="mt-4 space-y-3"><EvidenceRow label="Rule snapshot" value={hasRuleSnapshot ? "Immutable and attached" : "Not attached"} ready={hasRuleSnapshot} /><EvidenceRow label="Review configuration" value={`${evidence.configuration_snapshot.length} retained section${evidence.configuration_snapshot.length === 1 ? "" : "s"}`} ready={evidence.configuration_snapshot.length > 0} /><EvidenceRow label="Execution scope" value={executionScopeSummary(evidence.execution_plan)} ready={Boolean(evidence.execution_plan)} /></div></section><section className="rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><div className="flex items-center gap-2"><ReceiptText className="size-4 text-[var(--ls-accent)]" /><h2 className="font-semibold text-[var(--ls-text)]">Publication receipts</h2></div><div className="mt-4 divide-y divide-[var(--ls-line)]">{evidence.receipts.length ? evidence.receipts.map((receipt) => <div className="py-3" key={receipt.id}><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium capitalize text-[var(--ls-text)]">{receipt.receipt_kind.replaceAll("_", " ")}</span><span className={receipt.published_at ? "text-[var(--ls-success-text)]" : "text-[var(--ls-warning-text)]"}>{receipt.published_at ? "Published" : "Pending"}</span></div><p className="mt-1 break-all font-mono text-[11px] text-[var(--ls-text-tertiary)]">{receipt.stable_marker} · {receipt.payload_hash.slice(0, 12)}</p></div>) : <Empty title="No publication receipts" detail="No provider write receipt is attached." />}</div></section><ExecutionScope plan={evidence.execution_plan} run={evidence.run} /></div>; }

function Logs({ evidence }: { evidence: ReviewEvidence }) { return <section className="rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><h2 className="text-base font-semibold text-[var(--ls-text)]">Safe operational log</h2><p className="mt-1 text-sm leading-6 text-[var(--ls-text-secondary)]">Only redacted durable events are available. Raw provider bodies, credentials, and private model reasoning are never returned here.</p><div className="mt-5 space-y-2">{evidence.events.length ? evidence.events.map((event) => <details className="rounded-[12px] border border-[var(--ls-line)] bg-[var(--ls-surface-muted)]" key={event.id}><summary className="luminous-focus flex cursor-pointer list-none items-center justify-between gap-4 rounded-[12px] px-4 py-3"><span className="text-sm font-medium text-[var(--ls-text)]">{event.event_type.replaceAll("_", " ")}</span><span className="text-xs text-[var(--ls-text-tertiary)]">r{event.revision} · {formatTime(event.created_at)}</span></summary><pre className="overflow-x-auto border-t border-[var(--ls-line)] p-4 font-mono text-[11px] leading-5 text-[var(--ls-text-secondary)]">{JSON.stringify(event.payload, null, 2)}</pre></details>) : <Empty title="No safe log events" detail="The control plane did not return retained events." />}</div></section>; }

function Findings({ evidence }: { evidence: ReviewEvidence }) { return <section className="overflow-hidden rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)]"><div className="border-b border-[var(--ls-line)] p-5"><h2 className="font-semibold text-[var(--ls-text)]">Run findings</h2><p className="mt-1 text-sm text-[var(--ls-text-secondary)]">Every finding remains bound to the exact reviewed revision.</p></div>{evidence.findings.length ? <div className="divide-y divide-[var(--ls-line)]">{evidence.findings.map((finding) => { const target = providerFileTarget({ ...evidence.run, path: finding.path, start_line: finding.start_line, end_line: finding.end_line }); const prompt = `Fix the ${finding.severity} ${finding.category} finding in ${evidence.run.repository}.\n\nExact revision: ${evidence.run.head_sha}\n\nLocation: ${finding.path}:${finding.start_line}-${finding.end_line}\n\nFinding: ${finding.body}${finding.suggestion ? `\n\nRecommended direction: ${finding.suggestion}` : ""}\n\nPreserve unrelated behavior and add focused verification.`; return <article className="p-5" key={finding.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.08em] text-[var(--ls-warning-text)]">{finding.severity} · {finding.category}</p>{target ? <a className="luminous-focus mt-1 inline-flex items-center gap-1 rounded font-mono text-sm text-[var(--ls-accent)] hover:underline" href={target.url} rel="noreferrer" target="_blank">{finding.path}:{finding.start_line}<ArrowUpRight className="size-3.5" /></a> : <p className="mt-1 font-mono text-sm text-[var(--ls-text)]">{finding.path}:{finding.start_line}</p>}</div><CopyEvidenceButton label="Copy prompt" value={prompt} /></div><p className="mt-3 text-sm leading-6 text-[var(--ls-text-secondary)]">{finding.body}</p>{finding.suggestion ? <details className="mt-3 rounded-[10px] bg-[var(--ls-surface-muted)] p-3"><summary className="cursor-pointer text-xs font-semibold text-[var(--ls-text)]">Recommended change</summary><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-[var(--ls-text-secondary)]">{finding.suggestion}</p></details> : null}</article>; })}</div> : <Empty title="No findings" detail="No actionable findings were retained for this run." />}</section>; }

function Timeline({ evidence }: { evidence: ReviewEvidence }) { return <section className="rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><h2 className="font-semibold text-[var(--ls-text)]">Immutable timeline</h2><ol className="mt-5 border-l border-[var(--ls-line-strong)] pl-6">{evidence.events.length ? evidence.events.map((event, index) => <li className="relative border-b border-[var(--ls-line)] py-4 first:pt-0 last:border-0" key={event.id}><span className={cn("absolute -left-[29px] top-5 size-2.5 rounded-full bg-[var(--ls-accent)] ring-4 ring-[var(--ls-surface)]", index === 0 && "top-1")} /><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="text-sm font-medium text-[var(--ls-text)]">{event.event_type.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[var(--ls-text-secondary)]">Revision {event.revision} · {event.actor_kind}{event.actor_subject ? ` · ${event.actor_subject}` : ""}</p></div><time className="text-xs text-[var(--ls-text-tertiary)]">{formatTime(event.created_at)}</time></div></li>) : <Empty title="No timeline events" detail="No durable transition events are attached." />}</ol></section>; }

function Back({ org }: { org: string }) { return <Link className="luminous-focus inline-flex items-center gap-2 rounded text-sm text-[var(--ls-text-secondary)] hover:text-[var(--ls-text)]" href={`/${org}/tasks?tab=running`}><ArrowLeft className="size-4" />Back to work queue</Link>; }
function TaskTabLink({ count, href, label, selected }: { count?: number; href: string; label: string; selected: boolean }) { return <Link aria-current={selected ? "page" : undefined} aria-selected={selected} className={cn("luminous-focus relative inline-flex h-11 shrink-0 items-center gap-2 rounded-t-[10px] px-4 text-sm font-medium", selected ? "text-[var(--ls-text)]" : "text-[var(--ls-text-secondary)] hover:bg-[var(--ls-surface-muted)]")} href={href} role="tab" tabIndex={selected ? 0 : -1}>{label}{count !== undefined ? <span className="rounded-full bg-[var(--ls-surface-muted)] px-1.5 py-0.5 text-[10px] text-[var(--ls-text-tertiary)]">{count}</span> : null}{selected ? <span className="absolute inset-x-2 bottom-0 h-0.5 rounded-full bg-[var(--ls-accent)]" /> : null}</Link>; }
function Metric({ icon: Icon, label, mono, value }: { icon: typeof Clock3; label: string; mono?: boolean; value: string }) { return <div className="rounded-[14px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-4"><Icon className="size-4 text-[var(--ls-accent)]" /><p className="mt-3 text-[11px] text-[var(--ls-text-tertiary)]">{label}</p><p className={cn("mt-1 text-sm font-semibold text-[var(--ls-text)]", mono && "font-mono")}>{value}</p></div>; }
function EvidenceRow({ label, ready, value }: { label: string; ready: boolean; value: string }) { return <div className="flex items-center justify-between gap-3 rounded-[12px] bg-[var(--ls-surface-muted)] p-4"><span className="text-sm font-medium text-[var(--ls-text)]">{label}</span><span className={cn("text-xs", ready ? "text-[var(--ls-success-text)]" : "text-[var(--ls-warning-text)]")}>{value}</span></div>; }
function ExecutionScope({ plan, run }: { plan: ReviewEvidence["execution_plan"]; run: ReviewEvidence["run"] }) { if (!plan) return <section className="xl:col-span-2 rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><h2 className="font-semibold text-[var(--ls-text)]">Execution scope</h2><p className="mt-2 text-sm leading-6 text-[var(--ls-text-secondary)]">Legacy run — its admitted file plan was not retained, so this page cannot claim which files were analyzed.</p></section>; return <details className="xl:col-span-2 rounded-[16px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-5"><summary className="luminous-focus flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold text-[var(--ls-text)] [&::-webkit-details-marker]:hidden"><span>Execution scope</span><span className="rounded-full bg-[var(--ls-accent-soft)] px-2.5 py-1 text-xs font-medium capitalize text-[var(--ls-accent)]">{executionScopeSummary(plan)}</span></summary><div className="mt-4 border-t border-[var(--ls-line)] pt-4"><p className="text-sm leading-6 text-[var(--ls-text-secondary)]">The planner persisted this scope before model execution. Deferred files were not analyzed by this run and are not treated as reviewed evidence.</p>{plan.static_impact_signals?.length ? <div className="mt-4 rounded-[10px] border border-[var(--ls-line)] bg-[var(--ls-surface-muted)] p-3"><p className="text-sm font-semibold text-[var(--ls-text)]">Static impact signals</p><ul className="mt-2 space-y-1 text-xs leading-5 text-[var(--ls-text-secondary)]">{plan.static_impact_signals.map((signal) => <li key={signal}>• {signal}</li>)}</ul><p className="mt-2 text-[11px] leading-5 text-[var(--ls-text-tertiary)]">These are path-level reasons for the selected files below; runtime dependency reachability was not measured.</p></div> : null}<ul className="mt-4 max-h-56 space-y-1 overflow-y-auto rounded-[10px] bg-[var(--ls-surface-muted)] p-3 font-mono text-xs leading-5 text-[var(--ls-text-secondary)]">{plan.selected_paths.map((path) => { const target = providerFileTarget({ ...run, head_sha: run.head_sha, path }); return <li className="truncate" key={path}>{target ? <a className="luminous-focus inline-flex max-w-full items-center gap-1 rounded text-[var(--ls-accent)] hover:underline" href={target.url} rel="noreferrer" target="_blank"><span className="truncate">{path}</span><ArrowUpRight className="size-3 shrink-0" /></a> : path}</li>; })}</ul></div></details>; }
function executionScopeSummary(plan: ReviewEvidence["execution_plan"]) { return plan ? `${plan.mode} · ${plan.selected_paths.length} selected · ${plan.deferred_files} deferred` : "Legacy run · not retained"; }
function Empty({ detail, title }: { detail: string; title: string }) { return <div className="col-span-full grid min-h-36 place-items-center p-6 text-center"><div><History className="mx-auto size-5 text-[var(--ls-text-tertiary)]" /><h3 className="mt-3 text-sm font-semibold text-[var(--ls-text)]">{title}</h3><p className="mt-1 text-xs leading-5 text-[var(--ls-text-secondary)]">{detail}</p></div></div>; }
