export type UiLanguage = "en" | "zh-CN";

export const uiLanguageCookie = "open-review-ui-language";

export function normalizeUiLanguage(value: string | undefined): UiLanguage {
  return value === "zh-CN" ? "zh-CN" : "en";
}

const copy = {
  en: {
    skip: "Skip to main content",
    workspaces: "Workspaces",
    allWorkspaces: "All workspaces",
    createWorkspace: "Create workspace",
    review: "Review",
    policy: "Policy",
    operate: "Operate",
    search: "Jump to a page or workspace…",
    theme: "Theme",
    notifications: "Notifications",
    signOut: "Sign out",
    navigation: "Navigation",
    collapse: "Collapse navigation",
    expand: "Expand navigation",
    cockpit: "Cockpit",
    issues: "Issues",
    pullRequests: "Pull requests",
    agentWork: "Agent work",
    policyStudio: "Policy studio",
    enterprise: "Enterprise",
    language: "Interface language",
    preview: "Preview environment.",
    previewDetail: "Pull requests, Issues, checks, and findings shown here are sample records. This deployment does not read from or write to GitHub or GitLab.",
    openConnections: "Open connections",
    evidenceOperations: "Evidence-first operations",
    reviewCockpit: "Review cockpit",
    cockpitIntro: "Decide where attention belongs next. Counts are resolved from one current durable review per pull request, never a slice of retries.",
    activeReviews: "Active reviews",
    activeReviewsDetail: "Current pull requests that are queued, running, or awaiting a durable transition",
    needsAttention: "Needs attention",
    needsAttentionDetail: "Current pull requests whose latest review needs an explicit decision",
    closedReviews: "Closed reviews",
    closedReviewsDetail: "Current pull requests with a terminal review state",
    reviewPulse: "Review pulse",
    reviewPulseDetail: "One current review per pull request, ordered by control-plane time.",
    allReviews: "All reviews",
    governanceSignal: "Governance signal",
    governanceDetail: "Policy resolves into an immutable snapshot at admission. A pull request cannot rewrite its governance from the branch under review.",
    policyVersionDetail: "Rules are versioned and require explicit publication.",
    policyUnavailable: "Policy inventory unavailable",
    policyUnavailableDetail: "The policy inventory could not be verified. No rule-set count is inferred.",
    revisionHistory: "Revision-aware history",
    revisionHistoryDetail: "Only the exact reviewed revision is authoritative.",
    followUpDetail: "Review exact run evidence before changing policy.",
    openWorkQueue: "Open work queue",
    checkConnections: "Check connections",
    connectSource: "Connect source control",
    noReviewActivity: "No review activity is available",
    reviewIndexUnavailable: "Review index is unavailable",
    reviewWorkspace: "Review workspace",
    reviewsIntro: "One current review per pull request. Retries update this index row; exact revisions, findings, files, checks, receipts, and immutable activity remain on the review detail.",
    active: "Active",
    completed: "Completed",
    all: "All",
    currentRevision: "Current revision",
    trigger: "Trigger",
    updated: "Updated",
    reviewState: "Review state",
    issueInbox: "Issue inbox",
    configureIssueFormat: "Configure Issue format",
    providerTriage: "Provider triage",
    exploreFindings: "Explore findings",
    open: "Open",
    regressed: "Regressed",
    critical: "Critical",
    assignedToMe: "Assigned to me",
    resolved: "Resolved",
    suppressed: "Suppressed",
    searchIssues: "Search issues…",
    severity: "Severity",
    category: "Category",
    repository: "Repository",
    status: "Status",
    age: "Age",
    apply: "Apply",
    clearFilters: "Clear filters",
    occurrences: "Occurrences",
    repositoryFile: "Repository / file",
    currentReviews: "current pull-request reviews",
    openedBy: "opened by",
    run: "run",
    openIn: "Open in",
    searchPullRequests: "Search pull requests",
    searchPullRequestsHint: "Repository, PR, or failure",
    paginationAnchor: "Pagination is anchored to the current run revision.",
    previous: "Previous",
    next: "Next",
    reviewLanguage: "Review output language",
    reviewLanguageHelp: "Set at workspace or repository scope. New PR reviews freeze this language at admission; model findings, GitHub/GitLab comments, and check summaries use it. Existing runs keep their original language.",
    issueResponseLanguage: "Issue response language",
    issueResponseLanguageHelp: "Set separately from PR review language. Choose a fixed language or follow the Issue's language when it can be determined.",
  },
  "zh-CN": {
    skip: "跳转到主要内容",
    workspaces: "工作空间",
    allWorkspaces: "全部工作空间",
    createWorkspace: "创建工作空间",
    review: "审核",
    policy: "策略",
    operate: "运维",
    search: "搜索页面或工作空间…",
    theme: "主题",
    notifications: "通知",
    signOut: "退出登录",
    navigation: "导航",
    collapse: "收起导航",
    expand: "展开导航",
    cockpit: "概览",
    issues: "问题",
    pullRequests: "合并请求",
    agentWork: "Agent 任务",
    policyStudio: "策略中心",
    enterprise: "企业设置",
    language: "界面语言",
    preview: "预览环境。",
    previewDetail: "这里的合并请求、Issue、检查和发现项均为示例数据。此部署不会从 GitHub 或 GitLab 读取或写入数据。",
    openConnections: "打开连接设置",
    evidenceOperations: "证据优先的审核运营",
    reviewCockpit: "审核概览",
    cockpitIntro: "优先处理真正需要关注的事项。每个合并请求只统计当前有效的一次审核，不把重试记录重复计数。",
    activeReviews: "进行中的审核",
    activeReviewsDetail: "排队、执行中或等待状态落库的合并请求",
    needsAttention: "需要处理",
    needsAttentionDetail: "最新审核需要明确人工决策的合并请求",
    closedReviews: "已结束的审核",
    closedReviewsDetail: "审核已进入终态的合并请求",
    reviewPulse: "审核动态",
    reviewPulseDetail: "每个合并请求仅显示当前审核，按控制面时间排序。",
    allReviews: "全部审核",
    governanceSignal: "治理状态",
    governanceDetail: "策略在准入时固化为不可变快照。待审分支不能改写自身适用的治理策略。",
    policyVersionDetail: "规则有版本，发布必须显式确认。",
    policyUnavailable: "策略清单不可用",
    policyUnavailableDetail: "无法验证策略清单，因此不推断规则集数量。",
    revisionHistory: "按版本保留历史",
    revisionHistoryDetail: "只有实际审核过的准确版本才具有权威性。",
    followUpDetail: "修改策略前，请先查看准确的运行证据。",
    openWorkQueue: "打开工作队列",
    checkConnections: "检查连接",
    connectSource: "连接代码平台",
    noReviewActivity: "暂无审核活动",
    reviewIndexUnavailable: "审核索引不可用",
    reviewWorkspace: "审核工作台",
    reviewsIntro: "每个合并请求只显示当前审核。重试会更新这一行；准确版本、发现项、文件、检查、回执及不可变活动记录可在详情中查看。",
    active: "进行中",
    completed: "已完成",
    all: "全部",
    currentRevision: "当前版本",
    trigger: "触发方式",
    updated: "更新时间",
    reviewState: "审核状态",
    issueInbox: "问题收件箱",
    configureIssueFormat: "配置 Issue 格式",
    providerTriage: "平台 Issue 分析",
    exploreFindings: "查看发现项",
    open: "待处理",
    regressed: "再次出现",
    critical: "严重",
    assignedToMe: "分配给我",
    resolved: "已解决",
    suppressed: "已忽略",
    searchIssues: "搜索问题…",
    severity: "严重程度",
    category: "类别",
    repository: "仓库",
    status: "状态",
    age: "时间",
    apply: "应用",
    clearFilters: "清除筛选",
    occurrences: "出现次数",
    repositoryFile: "仓库 / 文件",
    currentReviews: "个当前合并请求审核",
    openedBy: "创建者",
    run: "运行",
    openIn: "在此打开：",
    searchPullRequests: "搜索合并请求",
    searchPullRequestsHint: "仓库、PR 或失败原因",
    paginationAnchor: "分页以当前运行版本为锚点。",
    previous: "上一页",
    next: "下一页",
    reviewLanguage: "PR 审核输出语言",
    reviewLanguageHelp: "可在工作空间或单个仓库设置。新 PR 审核准入时会冻结语言；模型发现项、GitHub/GitLab 评论和检查摘要均使用该语言。已有运行不会被改写。",
    issueResponseLanguage: "Issue 回复语言",
    issueResponseLanguageHelp: "与 PR 审核语言独立设置。可指定固定语言，也可在能够判断时跟随 Issue 原文语言。",
  },
} as const;

export type UiTextKey = keyof (typeof copy)["en"];

export function uiText(language: UiLanguage, key: UiTextKey): string {
  return copy[language][key];
}
