import type { UiLanguage } from "@/lib/ui-language";

// Source-English keys make authored copy explicit. Only call this for interface
// copy: provider text, approved requirements, code, hashes and receipts stay raw.
export const workflowCopy = {
  "Agent work": "Agent 任务",
  "Agent work unavailable": "Agent 任务暂不可用",
  "Check provider connection": "检查代码平台连接",
  "The control plane is unavailable.": "控制服务暂不可用。",
  "A governed Issue-to-PR control plane. Every request is classified first, then requires a bounded plan and explicit approval before a separately deployed coding executor can receive it.": "受审批治理的 Issue 到 PR 流程。每项请求先分类，再生成有范围限制的计划；明确批准后，独立部署的编码执行器才能接收任务。",
  "Provider Issue triage": "代码平台 Issue 分析",
  "Before the first Agent task": "开始 Agent 任务前",
  "Six independent gates. Creating a Draft does not guarantee review admission or a completed feedback cycle.": "六项独立检查。创建草稿不代表已经进入审核或完成反馈流程。",
  "Queue and worker evidence": "队列与工作进程证据",
  "Jev:": "Jev：",
  "Executor:": "执行器：",
  "Write credentials:": "写入凭据：",
  "Source:": "来源：",
  "pending ·": "待处理 ·",
  "failed. Execution:": "失败。执行：",
  "queued ·": "排队 ·",
  "running ·": "执行中 ·",
  "needing attention.": "需要处理。",
  "Tenant queue health is unavailable; zero visible tasks does not prove a healthy adapter.": "工作区队列健康信息不可用；未显示任务不能证明执行适配器正常。",
  "A signed adapter probe proves endpoint reachability only. Configuration, queue rows, and probe results do not prove model quality, sandbox isolation, provider write access, or a completed Draft PR.": "签名探测只证明适配器端点可达。配置、队列记录和探测结果不能证明模型质量、沙箱隔离、代码平台写入权限或草稿 PR 已完成。",
  "Coding Agent is not connected": "尚未连接编码 Agent",
  "Jev classifies an Issue; it cannot write code. A Manual repository policy may create a candidate, but approving a plan without a coding adapter will not produce a Draft PR/MR.": "Jev 负责 Issue 分类，不能编写代码。手动模式可创建候选任务；未连接编码适配器时，批准计划也不会产出草稿 PR/MR。",
  "Self-hosted operator setup": "私有部署配置",
  "Configure the separate runner connection (": "配置独立执行器连接（",
  "and": "和",
  "), a reviewed per-job sandbox image, the Codex Responses model route/key, and an installation-scoped provider write credential. Keep all secrets on their designated server-side workers; do not enter them in the Console.": "）、经过审核的任务沙箱镜像、Codex Responses 模型路由与密钥，以及受安装范围限制的代码平台写入凭据。密钥应保存在对应服务端进程，不要填入控制台。",
  "Then confirm adapter reachability in Platform health and test one explicitly approved Issue before enabling labeled-Issue admission.": "在平台健康页面确认适配器可达，再验证一个明确批准的 Issue，之后才启用标签准入。",
  "Ask the deployment operator to connect the isolated coding adapter; workspace policy alone cannot enable it.": "请部署管理员连接隔离编码适配器；仅修改工作区策略不能启用它。",
  "Repository admission": "仓库准入",
  "No policy or Reserved mode admits tasks. Manual mode still requires an approved plan before a coding Agent can start.": "未配置策略或使用预留模式时，不接受任务。手动模式仍需先批准计划，编码 Agent 才能开始执行。",
  "policy first": "先配置策略",
  "Refreshing…": "刷新中…",
  "Retry unavailable sections": "重试不可用的部分",
  "Repository policy saved. Existing tasks remain subject to their frozen classification and plan approval.": "仓库策略已保存。已有任务仍遵循其冻结分类和计划审批。",
  "Showing the first 100 policies. Search and select any authorized repository above to load its exact policy and revision before editing.": "当前显示前 100 项策略。请在上方搜索并选择授权仓库，加载其准确策略版本后再编辑。",
  "No repositories are enabled for Agent tasks.": "尚未为任何仓库启用 Agent 任务。",
  "Connect and verify a Git provider": "连接并验证代码平台",
  "Repository policies could not be loaded. Editing is paused until their revisions are available.": "仓库策略加载失败。取得策略版本前暂停编辑。",
  "Agent task queue": "Agent 任务队列",
  "Created by a verified Issue command, an explicitly enabled Issue label, a bounded revise command on an Agent Draft, or a governed API request. No CLI execution occurs here.": "任务由已验证的 Issue 命令、明确启用的 Issue 标签、Agent 草稿的受限修订命令或受治理的 API 请求创建。此页面不执行 CLI。",
  "Live progress updates every 8 seconds while this tab is visible.": "页面可见时，每 8 秒更新一次实时进度。",
  "on page": "项在本页",
  "Refresh Agent tasks": "刷新 Agent 任务",
  "Refresh task status now": "立即刷新任务状态",
  "No older Agent tasks on this page. Return to the latest tasks below.": "本页没有更早的 Agent 任务。可在下方返回最新任务。",
  "No Agent tasks yet": "暂无 Agent 任务",
  "Connect and verify GitHub or GitLab before admitting Issue work.": "接受 Issue 任务前，请先连接并验证 GitHub 或 GitLab。",
  "Open Connections": "打开连接设置",
  "No repository currently accepts Agent task requests.": "当前没有仓库接受 Agent 任务请求。",
  "Select a verified repository and save Manual mode": "请选择已验证的仓库并保存手动模式",
  "first.": "后再继续。",
  "The policy overview reached its 100-item limit, so it cannot confirm whether another repository is enabled.": "策略概览已达到 100 项上限，无法确认其他仓库是否启用。",
  "Search and select the repository": "搜索并选择仓库",
  "to load its exact policy.": "以加载其准确策略。",
  "In a repository with Manual mode enabled, comment": "在启用手动模式的仓库中，评论",
  "on a normal Issue. The bot records the request, classifies the frozen Issue snapshot, and waits for a bounded plan and approval.": "到普通 Issue。机器人会记录请求，对冻结的 Issue 快照分类，然后等待受限计划和审批。",
  "Agent admission prerequisites could not be checked. Retry the unavailable provider connection or policy read before issuing a command.": "无法检查 Agent 准入前提。发布命令前，请重试不可用的平台连接或策略读取。",
  "The task queue could not be loaded. This is not an empty queue; retry without changing repository policy.": "任务队列加载失败，不能视为空队列。请重试，无需修改仓库策略。",
  "Agent task history": "Agent 任务历史",
  "Latest tasks": "最新任务",
  "Older tasks →": "更早的任务 →",
  "End of history": "已到最早记录",
  "Edit an existing repository policy": "编辑已有仓库策略",
  "Choose an existing policy or search below": "选择已有策略或在下方搜索",
  "Selection verifies the repository inventory and reloads the exact policy revision before saving.": "选择仓库后会验证仓库清单，并在保存前重新加载准确策略版本。",
  "Provider inventory unavailable": "代码平台仓库清单不可用",
  "Policy revision unavailable": "策略版本不可用",
  "Policy lookup returned an invalid result": "策略查询返回无效结果",
  "Policy lookup returned a different repository": "策略查询返回了其他仓库",
  "Select a repository from a verified provider inventory first.": "请先从已验证的平台清单中选择仓库。",
  "Wait for the exact repository policy revision before saving.": "取得准确的仓库策略版本后才能保存。",
  "The repository policy was not saved.": "仓库策略未保存。",
  "The repository policy was not saved. Check the connection and try again.": "仓库策略未保存。请检查连接后重试。",
  "This policy has no matching verified installation. Reconnect the provider before editing it.": "此策略没有匹配的已验证安装。编辑前请重新连接代码平台。",
  "Verified provider installation": "已验证的平台安装",
  "No verified connections": "没有已验证的连接",
  "Authorized scope:": "授权范围：",
  "· installation": "· 安装",
  "Task delivery workflow": "任务交付流程",
  "Auto-plan, verify and repair, re-review, then human acceptance": "自动计划、验证与修复、再审，最后人工验收",
  "Require independent evidence for every acceptance criterion": "每项验收条件必须有独立证据",
  "The fixed verifier must report a passing result for each criterion. A general test-suite pass alone cannot satisfy this option.": "固定验证器必须逐项报告通过结果；仅有整体测试通过不能满足此要求。",
  "Verification repair cycles": "验证修复轮数",
  "Total attempts across plans and feedback": "所有计划与反馈的执行次数上限",
  "Required independent CI checks, separated by commas": "必需的独立 CI 检查，以逗号分隔",
  "New tasks require a deployment-approved verification profile. Initial and repair plans still need owner/admin approval. Blocking findings, diagnosed code CI failures and owner acceptance feedback prepare repair tasks automatically. A blank CI list requires at least one independent check and all observed independent checks to pass. Existing task budgets stay frozen.": "新任务需要部署方批准的验证配置。初始与修复计划均需所有者或管理员批准。阻断发现、已诊断的代码 CI 失败及验收反馈会自动准备修复任务。CI 列表留空时，仍要求至少一项独立检查，且已观察到的独立检查全部通过。已有任务预算保持冻结。",
  "Agent executor profile": "Agent 执行器类型",
  "Frozen into each admitted Agent task": "每个准入任务都会冻结此配置",
  "Search authorized repositories": "搜索授权仓库",
  "Search by repository name, including beyond the first 500": "按仓库名称搜索，可查询前 500 项以外的仓库",
  "Showing up to 500 matches from this installation. Narrow the search to find larger inventories.": "最多显示此安装的 500 个匹配仓库。请缩小搜索范围以查询更多仓库。",
  "Verified repository": "已验证的仓库",
  "Loading repositories…": "加载仓库中…",
  "Repository inventory unavailable": "仓库清单不可用",
  "No matching repositories": "没有匹配的仓库",
  "No active repositories": "没有可用仓库",
  "Select a repository": "选择仓库",
  "Agent task admission mode": "Agent 任务准入模式",
  "Disabled": "已禁用",
  "Reserved — no tasks": "预留模式 — 不接受任务",
  "Reserved": "预留模式",
  "Manual": "手动模式",
  "Attempts": "执行次数",
  "Maximum attempts": "执行次数上限",
  "Maximum isolated executions for one approved plan": "一个已批准计划的隔离执行次数上限",
  "Minutes": "分钟",
  "Maximum execution minutes": "执行时间上限（分钟）",
  "Maximum wall-clock time for one isolated execution": "一次隔离执行的实际时间上限",
  "Policy revision unavailable; saving is paused.": "策略版本不可用，已暂停保存。",
  "Loading the exact repository policy revision…": "正在加载仓库的准确策略版本…",
  "Retry": "重试",
  "Decision backend": "决策服务",
  "Agent task decision backend": "Agent 任务决策服务",
  "TypeSafe Jev (default)": "TypeSafe Jev（默认）",
  "Rules only (legacy/offline)": "仅规则（旧版/离线）",
  "Hosted Jev sends verified Issue evidence to TypeSafe. Configure the selected endpoint on the source worker; a missing or invalid response stops admission. No automatic execution is enabled.": "托管 Jev 会将已验证的 Issue 证据发送给 TypeSafe。请在来源工作进程配置端点；缺失或无效响应会阻止准入。此设置不会启用自动执行。",
  "Create candidate from labeled Issues": "从带标签的 Issue 创建候选任务",
  "Automatic Agent admission label": "Agent 自动准入标签",
  "Creates only a governed candidate. Source capture, decision evaluation, and owner/admin plan approval still block every executor.": "只创建受治理的候选任务。所有执行器仍需通过来源捕获、决策评估和所有者或管理员计划审批。",
  "Limits are frozen when a task is created: at most": "任务创建时会冻结限制：最多",
  "isolated execution": "次隔离执行",
  ", each capped at": "，每次上限",
  "minutes with the": "分钟，执行器为",
  "profile. Manual mode still requires classification, a bounded plan, and owner/admin approval.": "。手动模式仍需分类、受限计划及所有者或管理员批准。",
  "Bounded manual Draft PR feedback cycles": "草稿 PR 的人工反馈轮数限制",
  "One revision": "一次修订",
  "Two revisions": "两次修订",
  "Three revisions": "三次修订",
  "A trusted": "可信的",
  "on the Draft PR starts a new plan-and-approval cycle; it never auto-runs or merges.": "草稿 PR 命令会启动新的计划与审批流程，不会自动执行或合并。",
  "Saving…": "保存中…",
  "Save repository policy": "保存仓库策略",
  "· manual feedback disabled": "· 人工反馈未启用",
  "decision ·": "决策 ·",
  "min maximum": "分钟上限",
  "· revision": "· 版本",
  "· requested by": "· 请求人",
  "frozen envelope ·": "冻结约束 ·",
  "min": "分钟",
  "pull request": "合并请求",
  "Task detail unavailable": "任务详情不可用",
  "The selected task could not be loaded. The task queue and repository policies remain independent.": "所选任务加载失败。任务队列和仓库策略仍可独立使用。",
  "Back to task queue": "返回任务队列",
  "Select an Agent task": "选择 Agent 任务",
  "Classification evidence, plans and owner approval stay together with the exact provider source revision.": "分类证据、计划和所有者审批均绑定代码平台的准确来源版本。",
  "Agent task": "Agent 任务",
  "Task ID": "任务 ID",
  "Copy task ID": "复制任务 ID",
  "Frozen policy v": "冻结策略版本",
  "· up to": "· 最多",
  "min per attempt": "分钟/次",
  "· manual Draft PR feedback disabled": "· 草稿 PR 人工反馈未启用",
  "Execution budget ·": "执行预算 ·",
  "Shared by the original task and all feedback cycles:": "原任务及所有反馈轮次共享：",
  "successful delivery": "次成功交付",
  "successful deliveries": "次成功交付",
  "attempt needs attention": "次执行需要处理",
  "attempts need attention": "次执行需要处理",
  "Execution held before starting": "执行前已阻止启动",
  "Blocking review result": "阻断审核结果",
  "Original review feedback": "原审核反馈",
  "This repair is bound to the retained repair evidence and exact Draft commit. The current Draft is checked again before execution and publication; this plan requires its own approval.": "修复绑定保留的修复证据和准确草稿提交。执行和发布前会再次检查当前草稿；此计划需要单独批准。",
  "Inspect the exact review findings": "查看准确审核发现",
  "View exact comment in": "查看原评论：",
  "A safe provider comment link is unavailable for this installation.": "此安装无法提供安全的代码平台评论链接。",
  "Admission decision": "准入决策",
  "rule score": "规则评分",
  "Admission action recorded:": "已记录的准入动作：",
  "Model advisory — not execution approval": "模型建议 — 执行仍需审批",
  "Deterministic admission checks ·": "确定性准入检查 ·",
  "Immutable source": "不可变来源",
  "Code review of Agent changes": "Agent 变更的代码审核",
  "PR #": "PR #",
  "No review run is linked to this exact Agent commit yet. Check webhook delivery and the repository's Draft review policy; marking the PR ready or explicitly requesting a review can start the normal review flow when reviews are enabled.": "尚无审核绑定此 Agent 的准确提交。请检查 Webhook 交付和仓库草稿审核策略；已启用审核时，可将 PR 标为就绪或明确请求审核来启动正常流程。",
  "Repository review settings": "仓库审核设置",
  "A linked review is analysis evidence, not permission to merge. Branch protection and human approval remain authoritative.": "关联审核提供分析证据；合并仍受分支保护和人工审批约束。",
  "Use": "请使用",
  "rather than overriding this classification in the Console.": "处理，不要在控制台覆盖此分类。",
  "Retry acknowledgement or source": "重试确认或来源读取",
  "Source retry was not accepted. Refresh the task and try again.": "来源重试未被接受。请刷新任务后重试。",
  "Recovery queued. Open Review will retry a missing provider acknowledgement first; otherwise it will re-read the source. No coding Agent has started.": "恢复已入队。Open Review 会先补充缺失的平台确认，否则重新读取来源；尚未启动编码 Agent。",
  "Recovery could not be queued. Check the control plane and try again.": "恢复无法入队。请检查控制服务后重试。",
  "Stop task": "停止任务",
  "This supersedes the current lease and rejects late result callbacks. A provider write already in flight may still create a Draft PR/MR; verify the repository after stopping. Audit evidence is retained.": "此操作会使当前租约失效并拒绝迟到回调。进行中的平台写入仍可能创建草稿 PR/MR；停止后请核对仓库。审计证据会保留。",
  "Why should this task stop?": "停止此任务的原因是什么？",
  "Stop this task": "停止此任务",
  "The task could not be stopped. Refresh and try again.": "任务未能停止。请刷新后重试。",
  "Agent task cancelled and its adapter lease superseded. Late results will not complete this task. If a provider write was already in flight, check the repository for a Draft PR/MR and close it if necessary.": "Agent 任务已取消，适配器租约已失效。迟到结果不能完成此任务。若平台写入已开始，请检查仓库中的草稿 PR/MR，必要时手动关闭。",
  "The task could not be stopped. Check the connection and try again.": "任务未能停止。请检查连接后重试。",
  "Earlier execution attempts ·": "此前执行记录 ·",
  "Execution attempt": "执行记录",
  "No execution lease has been claimed. Approval remains a governed queue handoff, not proof that a coding Agent has started.": "尚未领取执行租约。审批只完成受治理的队列交接，不能证明编码 Agent 已启动。",
  "attempt": "次执行",
  "· task revision": "· 任务版本",
  "· plan revision": "· 计划版本",
  "Execution deadline ·": "执行截止时间 ·",
  "adapter job ·": "适配器作业 ·",
  "Validated commit checkpoint · provider publication unconfirmed": "已验证的提交检查点 · 平台发布尚未确认",
  "Attempt": "执行",
  "retained this evidence before pushing. It does not prove that a branch or Draft PR/MR exists.": "在推送前保留了此证据。它不能证明分支或草稿 PR/MR 已存在。",
  "Patch SHA-256": "补丁 SHA-256",
  "file(s) ·": "个文件 ·",
  "diff byte(s)": "差异字节",
  "Inspect the provider branch and Draft before approving another attempt. This checkpoint must not be treated as a completed review.": "批准再次执行前，请检查平台分支和草稿。此检查点不能视为已完成的审核。",
  "Draft pull request reported by adapter": "适配器报告的草稿合并请求",
  "Validated patch SHA-256 ·": "已验证补丁 SHA-256 ·",
  "Open draft pull request": "打开草稿合并请求",
  "This is execution evidence only. Normal review and merge gates still apply.": "此处仅为执行证据，仍需通过正常审核与合并门禁。",
  "Next step: deploy the isolated adapter, then submit and approve a new bounded plan revision.": "下一步：部署隔离适配器，再提交并批准新的受限计划版本。",
  "Next step: inspect the adapter and provider evidence, resolve the reported failure, then submit and approve a new bounded plan revision.": "下一步：查看适配器和代码平台证据，解决已报告故障，再提交并批准新的受限计划版本。",
  "No deployment-approved repository command is attested for this attempt.": "本次执行没有部署方批准的仓库命令证明。",
  "Approved repository command passed · evidence": "批准的仓库命令已通过 · 证据",
  "One deployment-approved command exited successfully in the verification sandbox. This is not product acceptance or a complete CI/security/UI check.": "一个部署方批准的命令在验证沙箱中成功退出；产品验收及完整 CI、安全和界面检查仍需独立完成。",
  "Profile SHA-256 ·": "配置 SHA-256 ·",
  "Output SHA-256 ·": "输出 SHA-256 ·",
  "byte(s)": "字节",
  "Bounded plan": "受限计划",
  "Objective": "目标",
  "Scope and impact": "范围与影响",
  "Verification": "验证",
  "Risks": "风险",
  "Unknowns": "待确认事项",
  "Full frozen requirements": "完整冻结需求",
  "Repository evidence at the frozen commit": "冻结提交的仓库证据",
  "revision": "版本",
  "Exact plan SHA-256": "准确计划 SHA-256",
  "Copy SHA": "复制 SHA",
  "Approve from the Issue instead": "通过 Issue 审批",
  "Copy command": "复制命令",
  "Review the complete plan first. Post this on the exact Issue revision using a provider account mapped to a workspace owner or admin.": "请先阅读完整计划。使用映射到工作区所有者或管理员的平台账号，将命令发布到准确的 Issue 版本。",
  "Approve exact revision": "批准准确版本",
  "Submit a new plan revision": "提交新计划版本",
  "Write a bounded, reviewable plan": "编写范围明确、可审核的计划",
  "The new revision replaces any plan still awaiting approval. A failed execution requires a fresh owner/admin approval; it cannot silently rerun the previous plan.": "新版本会替代尚待审批的计划。执行失败后需所有者或管理员重新批准，不能静默重跑旧计划。",
  "A plan is not a shell prompt and cannot start a coding Agent without separate owner/admin approval.": "计划不是 Shell 提示词；需所有者或管理员单独批准后才能启动编码 Agent。",
  "Describe the outcome and observed behavior…": "描述目标结果和已观察到的行为…",
  "Name the files, dependencies, boundaries, and exclusions…": "列出文件、依赖、范围边界和排除项…",
  "List tests and checks required before a Draft PR…": "列出创建草稿 PR 前必须完成的测试与检查…",
  "State the rollback and safety concerns; use None with a reason if applicable…": "说明回滚和安全风险；无风险时请说明理由…",
  "List open questions or explain why none remain…": "列出待确认问题，或说明为何已无待确认事项…",
  "Acceptance criteria (one per line)": "验收条件（每行一项）",
  "Complete every section; each accepts up to 4,000 UTF-8 bytes. This exact content is frozen and hashed for approval.": "请填写全部章节，每项最多 4,000 个 UTF-8 字节。审批时会冻结准确内容并计算哈希。",
  "Submit revision for approval": "提交版本以供审批",
  "Save plan for approval": "保存计划以供审批",
  "The plan was not saved. Refresh and try again.": "计划未保存。请刷新后重试。",
  "Plan recorded. It now waits for explicit owner/admin approval.": "计划已记录，正在等待所有者或管理员明确批准。",
  "The plan was not saved. Check the connection and try again.": "计划未保存。请检查连接后重试。",
  "The plan was not approved. Refresh and try again.": "计划未获批准。请刷新后重试。",
  "The exact plan revision is approved and durably queued. Watch the execution attempt for adapter acceptance or a needs-attention result; approval alone does not prove the coding Agent started.": "准确计划版本已获批准并持久化入队。请查看执行记录中的适配器接收或待处理结果；审批本身不能证明编码 Agent 已启动。",
  "The plan was not approved. Check the connection and try again.": "计划未获批准。请检查连接后重试。",
  "A workspace reviewer, admin, or owner must write the plan.": "计划须由工作区审核员、管理员或所有者编写。",
  "Only a workspace owner or admin may approve the plan.": "仅工作区所有者或管理员可以批准计划。",
  "A different owner or admin must approve this revision, or the workspace owner can enable Agent plan self-approval in Settings → Approvals.": "此版本须由其他所有者或管理员批准；工作区所有者也可在“设置 → 审批”中启用 Agent 计划自审批。",
  "No current plan revision is awaiting approval.": "当前没有等待审批的计划版本。",
  "The frozen branch execution budget is exhausted. A policy edit cannot expand this task; a new request needs its own source verification and approval.": "冻结的分支执行预算已用完。修改策略不能扩充本任务预算；新请求需重新验证来源并审批。",
  "This task state no longer accepts a new plan.": "当前任务状态不再接受新计划。",
  "Approval is unavailable until the current permissions and plan revision are reloaded.": "重新加载当前权限和计划版本后才能审批。",
  "Plan creation is unavailable until source verification and permissions are reloaded.": "重新加载来源验证和权限后才能创建计划。",
  "risk": "风险",
  "Draft delivered": "草稿已交付",
  "Requirement acceptance ·": "需求验收 ·",
  "Commit": "提交",
  "Recorded decision:": "已记录的决定：",
  ". Current checks must recover before it is effective.": "。当前检查恢复通过后，此决定才生效。",
  "Refresh independent CI": "刷新独立 CI",
  "Draft delivery is separate from requirement completion. Verify each criterion at this commit; owner or administrator approval is required.": "草稿交付与需求完成分别记录。请在此提交逐项核验条件，由所有者或管理员决定验收。",
  "Independent verifier:": "独立验证器：",
  "Test result or observation supporting this criterion": "支持此条件的测试结果或观察证据",
  "Decision reason": "决定理由",
  "Accept requirements": "接受需求",
  "Request changes": "要求修改",
  "Open the automatically prepared repair plan": "打开自动准备的修复计划",
  "The recorded feedback prepares a repair plan when the current Draft and budget allow it. Approve that plan; the updated commit will be verified and reviewed again.": "当前草稿和预算允许时，已记录反馈会生成修复计划。批准后，更新提交将再次验证和审核。",
  "Acceptance changed; refresh the task.": "验收状态已变化，请刷新任务。",
  "Requirement acceptance recorded for this exact commit.": "已记录此准确提交的需求验收决定。",
  "Changes recorded. A repair plan is prepared when the current Draft and frozen budget allow it.": "修改意见已记录。当前草稿和冻结预算允许时会准备修复计划。",
  "Acceptance could not be saved. Check the connection and retry.": "验收决定未能保存。请检查连接后重试。",
  "Check observation is not retryable.": "当前检查观察状态无法重试。",
  "Independent CI refresh queued. No coding Agent was started.": "独立 CI 刷新已入队；未启动编码 Agent。",
  "Check refresh could not be queued.": "检查刷新未能入队。",
  "Exact-commit review and independent CI passed; verify each acceptance criterion": "准确提交的审核及独立 CI 已通过，请逐项核验验收条件",
  "Recovered the existing owned Draft at the signed validated checkpoint by a fresh provider read; no coding or provider write was repeated. Original publication failure remains in recovery and audit records.": "通过新的代码平台只读查询，确认了签名验证检查点对应的已有自有草稿；未重复编码或平台写入。原发布失败仍保留在恢复及审计记录中。",
  "Review {state}": "审核{state}",
  "Execution budget · {used}/{limit}": "执行预算 · {used}/{limit}",
  "Frozen limits: {attempts} isolated execution(s), up to {minutes} minutes each, using {executor}. Manual mode requires classification, a bounded plan and owner/admin approval.": "冻结限制：最多 {attempts} 次隔离执行，每次最多 {minutes} 分钟，使用 {executor}。手动模式需分类、受限计划和所有者或管理员批准。",
  "Review complete · gate unknown": "审核完成 · 门禁未知",
  "Review complete · advisory only": "审核完成 · 仅建议",
  "Merge gate blocked": "合并门禁阻断",
  "Review gate passed": "审核门禁通过",
  "No trustworthy passing conclusion was published. Open the review for recovery guidance.": "未发布可信的通过结论。请打开审核查看恢复指引。",
  "Wait for the exact-revision review result before acting on findings or a merge gate.": "依据发现项或合并门禁操作前，请等待准确版本的审核结果。",
  "No immutable merge-gate decision was retained; this does not prove the Draft is clear to merge.": "未保留不可变门禁决定，不能据此确认草稿可合并。",
  "{count} recorded finding(s). Blocking was off for this revision; human approval and branch protection still apply.": "已记录 {count} 条发现。此版本未启用阻断，仍需遵循人工审批和分支保护。",
  "{count} finding(s) meet the {threshold} threshold. Open the review to inspect evidence, then update the Draft or request an approved Agent feedback cycle.": "有 {count} 条发现达到{threshold}阈值。请打开审核核对证据，再更新草稿或请求经过批准的 Agent 反馈修订。",
  "{count} recorded finding(s); none block at the {threshold} threshold. Human approval and branch protection still apply.": "已记录 {count} 条发现，没有达到{threshold}阻断阈值的发现。仍需遵循人工审批和分支保护。",
  "Author self-approval": "作者自审批",
  "Approval settings": "审批设置",
  "Workspace approval rules require a different approver by default.": "工作区审批规则默认要求作者以外的审批人。",
  "Approval settings unavailable": "审批设置暂不可用",
  "Sign in and check the service connection, then reload.": "请登录并检查服务连接后重新加载。",
  "Disabled by default. The workspace owner can enable this setting. Authors with the required role can then manually approve their own requests. Every setting change and approval is audited.": "默认禁止。工作区所有者可启用此设置；启用后，拥有审批角色的作者可手动批准自己的请求。每次设置变更和审批均记录审计。",
  "Allow Agent plan authors to approve their own plans": "允许 Agent 计划作者自审批",
  "Only owners or admins can approve; the exact plan revision and acceptance criteria must still be confirmed.": "仅所有者或管理员可以批准，仍须确认准确计划版本及验收条件。",
  "Allow rule version requesters to approve their own requests": "允许规则版本申请人自审批",
  "The rule approval role is still required. One vote per person, approval counts and content hashes remain enforced.": "仍须具备规则审批角色；每人仅一票，审批人数和内容哈希校验继续生效。",
  "These settings apply only to Agent plans and rule versions. Disabling blocks new self-approvals and preserves existing approvals. Model configuration, exceptions, rollouts and data governance still require a different approver.": "这两个设置仅适用于 Agent 计划和规则版本。关闭后阻止新的自审批，已有审批记录保留。模型配置、规则例外、灰度发布及数据治理仍要求独立审批人。",
  "Save approval settings": "保存审批设置",
  "Default configuration": "默认配置",
  "Only the workspace owner can change approval settings.": "仅工作区所有者可修改审批设置。",
  "Could not save approval settings.": "审批设置未能保存。",
  "Approval settings saved (revision {revision}).": "审批设置已保存（版本 {revision}）。",
  "Members": "成员",
  "Approvals": "审批",
  "Models & BYOK": "模型与自带密钥",
  "API & CLI keys": "API 与 CLI 密钥",
  "Data governance": "数据治理",
  "Platform health": "平台健康",
  "Enterprise settings": "企业设置",
  "Policy governance sections": "策略治理页面",
  "Library": "规则库",
  "Discovery": "规则发现",
  "Bindings": "绑定",
  "Test Lab": "测试实验室",
  "Exceptions": "例外",
  "Insights": "洞察",
  "Copy": "复制",
  "Copied": "已复制",
  "Copy failed": "复制失败",
  "No matching approval requests": "没有匹配的审批请求",
  "Submit a policy draft from the library to start governed approval.": "从规则库提交策略草稿，启动受治理的审批。",
  "Version": "版本",
  "requested by": "申请人",
  "distinct approver votes": "位不同审批人的投票",
  "Evidence and decision controls": "证据与审批操作",
  "Immutable content SHA-256": "不可变内容 SHA-256",
  "Version state": "版本状态",
  "Review note": "审核说明",
  "(optional)": "（可选）",
  "Record the evidence behind this decision.": "记录支持此决定的证据。",
  "Approve exact version": "批准准确版本",
  "Reject to draft": "拒绝并退回草稿",
  "Decision unavailable: rule approval permission is required and each reviewer votes once. Requester decisions require the workspace owner to enable rule self-approval in Settings → Approvals.": "无法审批：需要规则审批权限，且每位审核人只能投票一次。申请人审批自己的请求时，须由工作区所有者在“设置 → 审批”中启用规则自审批。",
  "Your recorded decision:": "你已记录的决定：",
  "Publish approved version": "发布已批准版本",
  "New policy draft": "新建策略草稿",
  "Compose structured review rules. The server validates the normalized rules before storing an immutable draft; publication still requires governed approval.": "编写结构化审核规则。服务端会验证规范化规则，再保存不可变草稿；发布仍需经过审批。",
  "Governance draft": "治理草稿",
  "Policy name": "策略名称",
  "Credential boundary": "凭据边界",
  "Purpose": "用途",
  "Explain the intent and expected review behavior.": "说明目的及预期审核行为。",
  "Rule": "规则",
  "Stable key": "稳定标识",
  "Enforcement": "执行方式",
  "Mandatory": "强制",
  "Advisory": "建议",
  "Severity": "严重程度",
  "Low": "低",
  "Medium": "中",
  "High": "高",
  "Critical": "严重",
  "Review instruction": "审核指令",
  "State the failure condition, evidence to inspect, and expected finding.": "说明失败条件、需检查的证据及预期发现。",
  "Add rule": "添加规则",
  "Creating draft": "正在创建草稿",
  "The control plane is not reachable with this signed-in session. Check the web service CONTROL_API_URL and the assigned tenant role.": "当前登录会话无法连接控制服务。请检查 Web 服务的 CONTROL_API_URL 和工作区角色。",
  "None": "无",
  "Preview an exact policy version": "预览准确策略版本",
  "Compile against one exact provider endpoint and current active bindings without creating a review run or writing to GitHub or GitLab.": "基于准确平台端点和当前生效绑定进行编译，不创建审核，也不向 GitHub 或 GitLab 写入。",
  "Policy version": "策略版本",
  "Select policy": "选择策略",
  "Repository": "仓库",
  "Provider": "代码平台",
  "Provider API URL": "代码平台 API 地址",
  "Target branch": "目标分支",
  "Candidate precedence": "候选优先级",
  "Results are evidence, not a release authorization. Approval and publication remain separate gates.": "结果用于提供证据，发布仍需分别经过审批与发布步骤。",
  "Run static preview": "运行静态预览",
  "Run an isolated historical replay": "运行隔离历史回放",
  "Re-run OCR on an exact completed PR revision with this immutable policy snapshot. The isolated worker has no publisher, check, or merge-gate capability.": "使用不可变策略快照，在准确的已完成 PR 版本上重新运行 OCR。隔离工作进程没有发布、检查或合并门禁能力。",
  "Provider writes disabled": "代码平台写入已禁用",
  "Historical source revision": "历史来源版本",
  "Select a completed review": "选择已完成的审核",
  "Run isolated OCR": "运行隔离 OCR",
  "No completed or needs-attention review is available as an immutable replay source.": "没有可作为不可变回放来源的已完成或待处理审核。",
  "Isolated run history": "隔离运行历史",
  "Active jobs continue after navigation. Refresh manually to read their latest durable state.": "离开页面后，运行中的作业仍会继续。请手动刷新以读取最新持久化状态。",
  "Refresh": "刷新",
  "Loading durable test receipts…": "正在加载持久化测试回执…",
  "findings": "条发现",
  "selected paths": "个选中路径",
  "deferred": "已延后",
  "snapshot": "快照",
  "No isolated replay has been requested for this workspace.": "此工作区尚未请求隔离回放。",
  "Effective rule delta": "有效规则差异",
  "Added": "新增",
  "Changed": "变更",
  "Removed": "移除",
  "Snapshot provenance": "快照来源",
  "Baseline SHA": "基线 SHA",
  "Candidate SHA": "候选 SHA",
  "Version content SHA": "版本内容 SHA",
  "Scope": "范围",
  "Historical sample envelope": "历史样本范围",
  "Runs": "运行数",
  "Findings": "发现数",
  "High risk": "高风险",
  "This is the available replay sample, not a replay result. No model call or provider comment occurred.": "此处显示可用的回放样本，尚无回放结果；没有调用模型或发布平台评论。",
  "Uncertainty and missing evidence (": "不确定性与缺失证据（",
  "Create rollout binding": "创建发布绑定",
  "Start a candidate in Shadow. Upgrades to an existing baseline use the evidence-gated Shadow & Canary flow below.": "候选版本先进入影子验证。已有基线升级时，使用下方基于证据的影子验证与灰度流程。",
  "Published policy": "已发布策略",
  "Select version": "选择版本",
  "Entire workspace": "整个工作区",
  "Initial state": "初始状态",
  "Shadow": "影子验证",
  "Canary": "灰度发布",
  "Active": "已生效",
  "Precedence": "优先级",
  "Target branch glob": "目标分支匹配模式",
  "Include paths": "包含路径",
  "Exclude paths": "排除路径",
  "Create binding": "创建绑定",
  "· precedence": "· 优先级",
  "Review rollout evidence": "查看发布证据",
  "Disable": "禁用",
  "No rollout bindings yet.": "暂无发布绑定。",
  "Evidence before exposure": "先验证证据，再开放流量",
  "Shadow & Canary": "影子验证与灰度发布",
  "Compare a matching published candidate without provider writes, then let a different owner or administrator approve a bounded Canary.": "在不写入代码平台的情况下比较匹配的已发布候选版本，再由另一位所有者或管理员批准受限灰度发布。",
  "rollout": "发布",
  "Start provider-silent Shadow": "启动不写入平台的影子验证",
  "Only a candidate with the same scope, branch, path filters and precedence can pair with the active baseline. The server also validates the rule set and versions.": "候选版本须与生效基线具有相同范围、分支、路径过滤和优先级。服务端还会验证规则集和版本。",
  "Active baseline": "生效基线",
  "Select baseline": "选择基线",
  "Shadow candidate": "影子候选版本",
  "Select matching candidate": "选择匹配的候选版本",
  "No matching Shadow binding exists. Create one above with the same scope and filters first.": "没有匹配的影子绑定。请先在上方创建范围和过滤条件一致的绑定。",
  "Start Shadow": "启动影子验证",
  "No Shadow or Canary rollout yet. Create a matching binding pair to begin collecting evidence.": "暂无影子验证或灰度发布。请创建匹配的绑定对以收集证据。",
  "Created by": "创建人",
  ". Existing run snapshots never change when this rollout changes state.": "。发布状态变化不会改写已有运行快照。",
  "Refresh evidence": "刷新证据",
  "Frozen Shadow comparison:": "冻结的影子比较：",
  ". Stable PR cohort; automatic rollback after": "。使用固定 PR 分组；自动回滚阈值为",
  "distinct failed candidate review": "个不同候选审核失败",
  "within": "观察窗口",
  "minutes. Historical run snapshots remain unchanged.": "分钟。历史运行快照保持不变。",
  "Rollback evidence:": "回滚证据：",
  "Loading provider-silent comparisons…": "正在加载不写入平台的比较…",
  "Latest replay evidence": "最新回放证据",
  "Baseline": "基线",
  "→ candidate": "→ 候选",
  "added · −": "新增 · −",
  "removed": "移除",
  "matched · run": "匹配 · 运行",
  "No replay result yet. The next matching completed review will queue a silent comparison; no provider comment or check is created by the replay.": "尚无回放结果。下一次匹配的已完成审核会入队静默比较；回放不会创建平台评论或检查。",
  "Approve a bounded Canary": "批准受限灰度发布",
  "A different workspace owner/admin must review this completed comparison. The API rejects self-approval and mismatched bindings.": "此完整比较须由其他工作区所有者或管理员审核。API 会拒绝自审批和不匹配的绑定。",
  "Initial traffic share": "初始流量比例",
  "1% pilot cohort": "1% 试点分组",
  "Failed PRs to roll back": "触发回滚的失败 PR 数",
  "1 distinct PR": "1 个不同 PR",
  "2 distinct PRs": "2 个不同 PR",
  "3 distinct PRs": "3 个不同 PR",
  "Observation window": "观察窗口",
  "15 minutes": "15 分钟",
  "1 hour": "1 小时",
  "4 hours": "4 小时",
  "Only candidate-selected execution failures count; quota rejections and repeated heads of one PR do not. Rollback changes future admissions only.": "仅统计选中候选版本后的执行失败；配额拒绝和同一 PR 的重复提交不计入。回滚只影响后续准入。",
  "I reviewed the comparison and accept exposure for future reviews.": "我已审核比较结果，并同意将候选版本用于后续审核。",
  "Start Canary": "启动灰度发布",
  "A Canary already uses this candidate. Pause or roll it back before starting another.": "此候选版本已有灰度发布。请先暂停或回滚，再启动新的灰度。",
  "Stage started": "阶段开始时间",
  ". Advancing requires the full": "。推进阶段须经过完整的",
  "-minute observation window, at least one completed candidate-selected PR/MR review, and no failed or in-flight candidate reviews. Promotion also requires a different owner/admin from the Canary creator.": "分钟观察窗口，至少完成一个选中候选版本的 PR/MR 审核，且没有失败或进行中的候选审核。正式提升还需由灰度创建人以外的所有者或管理员批准。",
  "Pause": "暂停",
  "Resume": "恢复",
  "Advance to": "推进至",
  "Promote candidate": "提升候选版本",
  "Roll back": "回滚",
  "Candidate is the default binding for future reviews.": "候选版本已成为后续审核的默认绑定。",
  "Request a bounded exception": "申请受限例外",
  "The rule key must exist in the selected published version. Requests cannot be self-approved.": "规则标识必须存在于所选已发布版本中。申请不能自行批准。",
  "Linked issue revision": "关联问题版本",
  "Published version": "已发布版本",
  "Exact rule key": "准确规则标识",
  "Expires at": "到期时间",
  "Risk acceptance reason": "风险接受理由",
  "Why the exception is necessary and what compensating control exists": "说明例外的必要性及补偿控制措施",
  "Ticket URL": "工单地址",
  "Request exception": "申请例外",
  "Expires": "到期",
  "Requested by": "申请人",
  "Decided by": "审批人",
  "Source issue · revision": "来源问题 · 版本",
  "Ticket": "工单",
  "Approve": "批准",
  "Reject": "拒绝",
  "Revoke": "撤销",
  "No policy exceptions have been requested.": "尚未申请策略例外。",
  "Required approvals": "所需审批人数",
  "Submit for approval": "提交审批",
  "Open approval queue": "打开审批队列",
  "This immutable version is available for scoped bindings.": "此不可变版本可用于范围绑定。",
  "Catalog unavailable": "规则目录不可用",
  "Core catalog · release-pinned": "核心规则目录 · 随版本固定",
  "Templates are compiled into this Open Review release. Installation creates a normal draft only; approvals, publication, and scoped bindings remain separate decisions.": "模板内置于当前 Open Review 版本。安装仅创建普通草稿；审批、发布和范围绑定仍需分别决定。",
  "Content verified": "内容已验证",
  "No catalog entries in this release": "当前版本没有目录条目",
  "Installed": "已安装",
  "Version & provenance": "版本与来源",
  "Release": "发布版本",
  "Source": "来源",
  "Digest": "摘要",
  "Open governed policy": "打开治理策略",
  "Configured only": "仅已配置",
  "Not configured": "未配置",
  "Not observed": "未观察到",
  "Adapter reachable": "适配器可达",
  "Mixed reachability": "部分可达",
  "Adapter unreachable": "适配器不可达",
  "Provider connection": "代码平台连接",
  "Connection detail": "连接详情",
  "Connections": "连接",
  "Set policy": "设置策略",
  "Jev classification": "Jev 分类",
  "Worker configuration is not proof of a successful model decision.": "工作进程配置不能证明模型决策已成功。",
  "Decision health": "决策服务健康",
  "Coding executor": "编码执行器",
  "A separate sandbox, model broker and scoped write credentials are needed after plan approval.": "计划批准后，还需独立沙箱、模型代理和受范围限制的写入凭据。",
  "Executor health": "执行器健康",
  "Write-credential broker": "写入凭据代理",
  "A private process heartbeat does not prove scoped token issuance or provider write access.": "私有进程心跳不能证明已签发受限令牌或拥有代码平台写入权限。",
  "Broker health": "凭据代理健康",
  "Draft review handoff": "草稿审核交接",
  "Connection settings": "连接设置",
  "Review filters": "审核过滤",
  "Review settings": "审核设置",
  "Choose repository": "选择仓库",
  "Fresh source-worker configuration evidence is unavailable.": "没有最新的来源工作进程配置证据。",
  "Fresh runner configuration evidence is unavailable.": "没有最新的执行器配置证据。",
  "Fresh private broker heartbeat evidence is unavailable.": "没有最新的私有凭据代理心跳证据。",
  "This task was cancelled. The plan is retained as evidence and can no longer be approved.": "任务已取消。计划作为证据保留，不能再批准。",
  "Agent Draft feedback": "Agent 草稿反馈",
  "Verifying the original feedback comment, current Agent Draft head, and exact base commit. Planning stays unavailable until this evidence is captured.": "正在验证原反馈评论、当前 Agent 草稿提交和准确基线提交。取得证据前不能规划任务。",
  "Open Review could not complete the provider acknowledgement, verify the Agent Draft and original feedback comment, or finish the decision check. Planning and execution remain blocked. Retry re-reads the current Draft and comment; it cannot reuse stale feedback.": "Open Review 未能完成平台确认、Agent 草稿与原反馈验证或决策检查。计划和执行仍被阻止。重试会重新读取当前草稿及评论，不复用过期反馈。",
  "Address the stated reason, then post a new revise command on the current Agent-created Draft. Editing an old comment does not reauthorize this task.": "处理所述原因，再向当前 Agent 草稿发布新的修订命令。编辑旧评论不能重新授权此任务。",
  "Wait for the original feedback comment, Agent Draft head, and exact base commit to be verified before writing a plan.": "编写计划前，请等待原反馈评论、Agent 草稿提交及准确基线提交验证完成。",
  "This Agent Draft feedback classification does not permit a coding plan. Review the admission evidence first.": "此 Agent 草稿反馈分类不允许创建编码计划。请先查看准入证据。",
  "Resolving the provider Issue, default branch, and exact commit. Planning stays unavailable until this evidence is captured.": "正在解析平台 Issue、默认分支和准确提交。取得证据前不能规划任务。",
  "Open Review could not complete the provider acknowledgement, source verification, or decision check. Planning and execution remain blocked. Retry will restore the acknowledgement first if needed, then re-read the current Issue and base commit.": "Open Review 未能完成平台确认、来源验证或决策检查。计划和执行仍被阻止。重试会先恢复必要确认，再读取当前 Issue 和基线提交。",
  "Update the provider Issue and submit a new implementation request for its current revision.": "请更新代码平台 Issue，并针对当前版本提交新的实现请求。",
  "Wait for the provider Issue and exact base commit to be verified before writing a plan.": "编写计划前，请等待平台 Issue 和准确基线提交验证完成。",
  "This Issue classification does not permit a coding plan. Review the admission evidence first.": "此 Issue 分类不允许创建编码计划。请先查看准入证据。",
  "Policy unknown": "策略未知",
  "The selected task's exact repository policy could not be read. Another repository's Manual policy does not apply.": "无法读取所选任务的准确仓库策略，其他仓库的手动策略不能替代它。",
  "Suggestion only": "仅建议",
  "Not enabled": "未启用",
  "This exact repository is not in Manual mode; new Issue implementation requests cannot be admitted.": "此仓库未启用手动模式，无法接受新的 Issue 实现请求。",
  "Manual enabled": "手动模式已启用",
  "This task's exact repository policy allows explicit Issue implementation requests; plan approval and the executor remain separate gates.": "此任务的准确仓库策略允许明确的 Issue 实现请求；计划审批和执行器仍需分别检查。",
  "Unknown": "未知",
  "Repository policies or verified connections could not be loaded.": "仓库策略或已验证连接加载失败。",
  "At least one verified repository allows explicit Issue implementation requests. Select a task to inspect its exact policy.": "至少一个已验证仓库允许明确的 Issue 实现请求。请选择任务以检查其准确策略。",
  "Check repository": "检查仓库",
  "The overview is limited to 100 policies. Select a task for an exact repository lookup.": "概览最多显示 100 项策略。请选择任务查询准确仓库。",
  "Enable Manual mode on a verified repository before requesting Issue implementation.": "请求 Issue 实现前，请先为已验证仓库启用手动模式。",
  "Connection unknown": "连接未知",
  "Select a repository with a verified provider installation before checking Draft review admission.": "检查草稿审核准入前，请选择具有已验证平台安装的仓库。",
  "Automatic reviews off": "自动审核已关闭",
  "Enable automatic reviews on this provider connection for Agent-created Drafts.": "请为此平台连接启用自动审核，以接受 Agent 创建的草稿。",
  "Author scope limited": "作者范围受限",
  "This connection reviews only the OAuth user's PRs. An Agent-created Draft has a provider-bot author; choose all authors to admit it automatically.": "此连接仅审核 OAuth 用户的 PR。Agent 草稿由平台机器人创建；请选择所有作者，以便自动准入。",
  "Effective review settings or filters could not be loaded. Do not assume the Draft will enter review.": "无法加载有效审核设置或过滤条件，不能假定草稿会进入审核。",
  "Manual reviews only": "仅人工触发审核",
  "Automatic webhook admission is disabled for this repository. An explicit review command would still be needed.": "此仓库已关闭自动 Webhook 准入，仍需明确的审核命令。",
  "Drafts excluded": "已排除草稿",
  "Enable Review drafts so the Agent-created Draft PR/MR starts a review before it is marked ready.": "请启用“审核草稿”，使 Agent 草稿 PR/MR 在标为就绪前开始审核。",
  "Push re-review off": "推送后再审已关闭",
  "Enable Re-review on push so an Agent fix can receive another review on its new head commit.": "请启用“推送后再审”，使 Agent 修复后的新提交再次审核。",
  "Check required labels": "检查必需标签",
  "Review admission requires PR/MR labels. Verify the Agent-created Draft receives them; otherwise the webhook will be skipped.": "审核准入要求 PR/MR 标签。请确认 Agent 草稿具有这些标签，否则 Webhook 会被跳过。",
  "Check author filter": "检查作者过滤",
  "This repository excludes selected authors. Verify the Agent Draft's provider-bot author is not excluded before relying on automatic review.": "此仓库排除了部分作者。依赖自动审核前，请确认 Agent 草稿的平台机器人作者未被排除。",
  "Branch unverified": "分支未验证",
  "Select an Agent task with a captured target branch to verify that its Draft can enter automatic review.": "请选择已捕获目标分支的 Agent 任务，以验证草稿能否进入自动审核。",
  "Branch filter unverified": "分支过滤未验证",
  "Target branch excluded": "目标分支已排除",
  "The target branch {branch} may match a wildcard filter. Confirm it in Filters; this UI does not evaluate the backend's glob rules.": "目标分支 {branch} 可能匹配通配符过滤。请在过滤设置中确认；此界面不计算服务端的匹配规则。",
  "The target branch {branch} is not listed in the review admission filter. Add it or choose an admitted target branch.": "目标分支 {branch} 不在审核准入过滤列表中。请添加它或选择已准入的目标分支。",
  "Core policy configured": "核心策略已配置",
  "Known Draft, push re-review, author and exact target-branch settings allow automatic admission. Webhook delivery and an actual review cycle still require live verification.": "当前草稿、推送再审、作者及准确目标分支设置允许自动准入。Webhook 交付和真实审核流程仍需实测。",
  "The selected task's exact installation could not be read. Do not infer its state from another connection or the bounded overview.": "无法读取所选任务的准确安装，不应根据其他连接或受限概览推断状态。",
  "Exact connection unavailable": "准确连接不可用",
  "The selected task's original installation is absent, inactive, unverified, or outside the current repository scope. Another connection cannot prove this task is ready.": "所选任务的原安装不存在、已停用、未验证或不在当前仓库范围内。其他连接不能证明此任务就绪。",
  "The selected task's original verified installation is absent, inactive, outside the current repository scope, or beyond the loaded list. Another connection cannot prove this task is ready.": "所选任务的原已验证安装不存在、已停用、不在仓库范围内或超出已加载列表。其他连接不能证明此任务就绪。",
  "Health unknown": "健康状态未知",
  "The task's original installation is verified, but its current provider access could not be sampled.": "任务的原安装已验证，但无法采样其当前平台访问状态。",
  "Read access observed": "已观察到读取权限",
  "The selected task's exact installation passed a fresh read-only probe. Provider write access is not proven by this check.": "所选任务的准确安装通过了新的只读探测；此检查不能证明平台写入权限。",
  "Probe failed": "探测失败",
  "The selected task's installation failed its latest provider access probe. Check its credential and endpoint before continuing.": "所选任务的安装未通过最新平台访问探测。继续前请检查凭据和端点。",
  "Needs attention": "需要处理",
  "The selected task's installation has degraded provider access or capabilities.": "所选任务安装的平台访问或能力已降级。",
  "Probe stale": "探测已过期",
  "The selected task's installation has no fresh read-only access result.": "所选任务安装没有最新的只读访问结果。",
  "Probe unavailable": "探测不可用",
  "The selected task's installation has no fresh read-only provider access result.": "所选任务安装没有最新的平台只读访问结果。",
  "Provider installations could not be loaded. Retry before admitting Issue work.": "平台安装加载失败。接受 Issue 任务前请重试。",
  "Not connected": "未连接",
  "Connect and verify a GitHub or GitLab installation with repository access.": "请连接并验证具有仓库访问权限的 GitHub 或 GitLab 安装。",
  "An installation is verified, but current provider access could not be sampled.": "安装已验证，但无法采样当前平台访问状态。",
  "All verified installations passed a fresh read-only probe. Provider write access is not proven by this check.": "全部已验证安装均通过新的只读探测；此检查不能证明平台写入权限。",
  "{observed}/{total} access observed": "已观察到 {observed}/{total} 项访问",
  "Only some verified installations passed a fresh read-only probe. Inspect the selected repository before requesting an Agent task.": "仅部分已验证安装通过新的只读探测。请求 Agent 任务前请检查所选仓库。",
  "A verified installation failed its latest provider access probe. Check its credential and endpoint health before requesting work.": "某个已验证安装未通过最新平台访问探测。请求任务前请检查凭据和端点健康状态。",
  "Provider access or an advertised capability is degraded. Inspect the selected installation before requesting work.": "平台访问或声明的能力已降级。请求任务前请检查所选安装。",
  "The last read-only provider probe is outside its freshness window. Recheck the connection before requesting work.": "最近一次平台只读探测已超出有效窗口。请求任务前请重新检查连接。",
  "An installation is verified, but no fresh read-only provider access result is available.": "安装已验证，但没有最新的平台只读访问结果。",
  "Pending": "待处理",
  "Approved": "已批准",
  "Rejected": "已拒绝",
  "Cancelled": "已取消",
  "All": "全部",
  "The action was rejected.": "操作被拒绝。",
  "The action failed.": "操作失败。",
  "Awaiting decision": "等待决定",
  "Ready to publish": "可发布",
  "Returned to draft": "已退回草稿",
  "Binding created. Admission will use it according to its lifecycle state.": "绑定已创建。准入将依据其生命周期状态使用此绑定。",
  "Binding could not be created.": "绑定未能创建。",
  "Binding state could not be updated.": "绑定状态未能更新。",
  "legacy provider": "旧平台配置",
  "all branches": "全部分支",
  "The policy template could not be installed.": "策略模板未能安装。",
  "This exact catalog release is already installed as a governed draft.": "此准确目录版本已作为治理草稿安装。",
  "Installed as a draft. Request governed approval before publishing or binding it.": "已安装为草稿。发布或绑定前请申请审批。",
  "The control plane did not return a trusted policy catalog.": "控制服务未返回可信的策略目录。",
  "Preview only": "仅预览",
  "Install as draft": "安装为草稿",
  "Admin approval required": "需要管理员批准",
  "Exception requested. A different rule manager must approve it before it can affect admission.": "例外已申请。由其他规则管理员批准后才能影响准入。",
  "Exception request could not be created.": "例外申请未能创建。",
  "Exception transition failed.": "例外状态转换失败。",
  "Binding unavailable": "绑定不可用",
  "Workspace": "工作区",
  "The rollout could not be created.": "发布流程未能创建。",
  "Shadow replay is active. The next matching completed review will produce a provider-silent comparison.": "影子回放已启用。下一次匹配的已完成审核将生成不写入平台的比较。",
  "Canary is active for future admissions. Existing reviews keep their frozen rule snapshots.": "灰度发布已对后续准入生效。已有审核保留冻结规则快照。",
  "Roll back this rollout? Future reviews will use the baseline. This rollout cannot be resumed.": "回滚此次发布？后续审核将使用基线；此发布不能恢复。",
  "Promote this candidate as the default rule? The baseline binding will be disabled for future reviews. Historical reviews will not change.": "将候选版本提升为默认规则？后续审核将禁用基线绑定，历史审核保持不变。",
  "The rollout state could not be changed.": "发布状态未能变更。",
  "Candidate promoted. Future reviews use its binding; retained run snapshots are unchanged.": "候选版本已提升。后续审核使用其绑定，保留的运行快照不变。",
  "Canary advanced to {percent}%. The new observation window starts now.": "灰度已推进至 {percent}%，新的观察窗口从现在开始。",
  "{mode} {state}. Only future review admissions change.": "{mode}{state}。仅影响后续审核准入。",
  "Shadow comparisons could not be loaded.": "影子比较加载失败。",
  "Shadow comparison": "影子比较",
  "legacy rollout — no approval evidence": "旧发布流程 — 无审批证据",
  "Identify whether this change exposes credentials, tokens, private keys, or personally identifiable data.": "说明此变更是否暴露凭据、令牌、私钥或可识别个人的信息。",
  "Name, rule key, and review instruction are required.": "请填写名称、规则标识和审核指令。",
  "The rule set was not accepted.": "规则集未被接受。",
  "Draft version {version} was created. Request governed approval before publishing it.": "草稿版本 {version} 已创建。发布前请申请审批。",
  "The rule set could not be created.": "规则集未能创建。",
  "Remove rule {number}": "移除第 {number} 条规则",
  "Mandatory rules use deny_override, so lower-precedence policies cannot weaken them.": "强制规则使用 deny_override，低优先级策略不能削弱它。",
  "Advisory rules replace lower-precedence versions with the same stable key.": "建议规则会替代具有相同稳定标识的低优先级版本。",
  "Create draft": "创建草稿",
  "The governance action was rejected.": "治理操作被拒绝。",
  "The action could not be completed.": "操作未能完成。",
  "The isolated run could not be created.": "隔离运行未能创建。",
  "The isolated run failed to start.": "隔离运行启动失败。",
  "The preview could not be generated.": "预览未能生成。",
  "The preview failed.": "预览失败。",
  "Static policy composition is valid": "静态策略组合有效",
  "Policy composition conflict": "策略组合冲突",
  "Baseline rules": "基线规则",
  "Candidate rules": "候选规则",
  "High / critical": "高 / 严重",
  "Not generated because composition failed": "因组合失败而未生成",
  "This {resource} revision is not eligible for Agent execution.": "此{resource}版本不符合 Agent 执行条件。",
  "More trusted {resource} context is required before planning.": "规划前还需更多可信的{resource}上下文。",
  "{count} rollout(s)": "{count} 项发布流程",
  "{count} distinct failed candidate review(s) within {minutes} minutes. Historical run snapshots remain unchanged.": "{minutes} 分钟内有 {count} 个不同候选审核失败。历史运行快照保持不变。",
  "attempts": "次尝试",
  "· feedback depth {depth}": " · 反馈层级 {depth}",
  "· up to {count} Draft PR feedback cycles": " · 最多 {count} 轮草稿 PR 反馈",
  "Version {version}": "版本 {version}",
  "Temporary risk acceptance for issue {id}: {body}": "Issue {id} 的临时风险接受：{body}",
  "Create, review, publish, and retire immutable review policies without losing the exact version used by any historical run.": "创建、审核、发布和停用不可变的审核策略，并保留每次历史运行使用的准确版本。",
  "Policy governance": "策略治理",
  "Rule library": "规则库",
  "Create rule": "创建规则",
  "Check connections": "检查连接",
  "Rule library unavailable": "规则库暂不可用",
  "Updated": "更新时间",
  "Immutable policy": "不可变策略",
  "Rule details": "规则详情",
  "Policy purpose": "策略用途",
  "Lifecycle": "生命周期",
  "Latest update": "最近更新",
  "Content identity": "内容标识",
  "Latest immutable version": "最新不可变版本",
  "Revision": "修订版本",
  "State": "状态",
  "Created": "创建时间",
  "Content SHA-256": "内容 SHA-256",
  "No immutable version is available.": "暂无不可变版本。",
  "Provenance boundary": "来源证据范围",
  "This view reports only identities returned by the control plane. Test evidence and bindings remain in their dedicated governed views.": "此页面仅显示控制服务返回的标识。测试证据和绑定仍在各自的治理页面中查看。",
  "Rule set ID": "规则集 ID",
  "Rule version ID": "规则版本 ID",
  "Rule-set author": "规则集作者",
  "Version author": "版本作者",
  "Manual review command": "手动审核命令",
  "This only runs when the current repository and target branch have an active binding for this published rule set.": "仅当当前仓库和目标分支存在此已发布规则集的生效绑定时，才会执行。",
  "Decide one immutable content hash. Requester decisions follow workspace self-approval settings; publication stays locked until quorum is met.": "对一个不可变内容哈希作出审批决定。申请人审批遵循工作区自审批设置；达到审批人数要求后才能发布。",
  "Approval governance": "审批治理",
  "Approval queue": "审批队列",
  "Every decision is bound to the displayed SHA-256. A changed payload requires a new version and approval request.": "每项决定都绑定到显示的 SHA-256。内容变更后需要新版本和新的审批申请。",
  "Scope immutable published versions, compare changes in Shadow, then expose a bounded Canary with independent evidence.": "为不可变的已发布版本设置范围，先进行影子比较，再依据独立证据执行受限灰度。",
  "Controlled rollout": "受控发布",
  "Policy bindings": "策略绑定",
  "State changes affect only future admissions. Existing review runs retain their exact immutable rule snapshot.": "状态变更仅影响后续准入。已有审核保留其准确的不可变规则快照。",
  "Browse only a tenant-approved policy catalog. Repository content and model suggestions never become a rule template without an explicit governed source.": "仅浏览工作区批准的策略目录。仓库内容和模型建议需具有明确的治理来源，才能成为规则模板。",
  "Rule discovery": "规则发现",
  "Request a time-bounded exception to one exact published rule key, require an independent decision, and retain every applied exception in future review snapshots.": "为已发布规则的准确标识申请有时限的例外，由独立人员作出决定，并在后续审核快照中保留每个应用的例外。",
  "Risk acceptance": "风险接受",
  "Policy exceptions": "策略例外",
  "Exceptions never edit a published policy. Approval affects only future admissions; expiry and revocation stop new use while historical snapshots remain unchanged. The expiry reconciler automatically restores a linked suppressed Issue and records its timeline.": "例外不修改已发布策略。批准仅影响后续准入；到期或撤销后停止新使用，历史快照保持不变。到期协调器会自动恢复关联的已抑制 Issue 并记录时间线。",
  "The source issue is unavailable, already resolved or suppressed, or your role cannot request a governed exception.": "来源 Issue 不可用、已解决或已抑制，或你的角色不能申请受治理的例外。",
  "Measure useful and false-positive signals from real review conversations while preserving repository and immutable rule-snapshot attribution.": "根据真实审核对话评估有效反馈和误报，并保留仓库与不可变规则快照的归属。",
  "Measured quality": "质量衡量",
  "Finding feedback": "发现项反馈",
  "Feedback is improvement evidence only. It never edits a published rule or changes a completed merge decision automatically.": "反馈仅作为改进证据，不会自动修改已发布规则或已完成的合并决定。",
  "Compile one exact rule version against a repository baseline, inspect deterministic deltas, and measure the available historical sample before approval.": "以仓库基线编译准确的规则版本，检查确定性的差异，并在审批前评估可用的历史样本。",
  "Policy evidence": "策略证据",
  "Preview and replay are read-only. They never publish provider comments, checks, or merge-gate status.": "预览和回放是只读操作，不会向代码平台发布评论、检查或合并门禁状态。",
  "Agent work from this Issue": "从此 Issue 创建 Agent 任务",
  "Turn this Issue into Agent work": "将此 Issue 转为 Agent 任务",
  "Creates a candidate from this exact Issue revision. A manual repository policy, source recheck, bounded plan, and owner/admin approval are required before coding can start.": "依据此准确的 Issue 版本创建候选任务。开始编码前，需要手动仓库策略、来源复查、受限计划，以及所有者或管理员批准。",
  "Open Agent task ·": "打开 Agent 任务 ·",
  "Agent tasks for this Issue snapshot": "此 Issue 快照的 Agent 任务",
  "Task": "任务",
  "Queueing retry": "正在加入重试队列",
  "Retry retained snapshot": "重试保留的快照",
  "Reuses revision r{revision} and its immutable model, prompt, and Issue-format snapshots.": "复用修订版本 r{revision} 及其不可变的模型、提示词和 Issue 格式快照。",
  "The Agent task could not be created. Refresh the Issue and retry.": "Agent 任务未能创建。请刷新 Issue 后重试。",
  "The Agent task could not be created. Check the connection and retry.": "Agent 任务未能创建。请检查连接后重试。",
  "The Issue analysis retry was rejected.": "Issue 分析重试被拒绝。",
  "The Issue analysis retry could not be queued.": "Issue 分析重试未能加入队列。",
  "Retry attempt {attempt} was already accepted.": "第 {attempt} 次重试已经被接受。",
  "Retry attempt {attempt} queued from the retained Issue snapshot.": "第 {attempt} 次重试已依据保留的 Issue 快照加入队列。",
  "The rule library could not be loaded. No policy absence or writable draft is inferred from this state.": "规则库加载失败。此状态不能证明没有策略或存在可编辑的草稿。",
  "Retired policies remain visible here for provenance when they exist.": "已停用策略会保留在此处，供来源追溯。",
  "Create a governed draft below. It remains non-executable until independently approved and published.": "在下方创建受治理的草稿。通过审批并发布前，草稿不可执行。",
  "No {tab} policies": "暂无{tab}策略",
  "No description was provided for this rule set.": "尚未填写此规则集的描述。",
  "The policy owner has not recorded a purpose statement.": "策略所有者尚未记录用途说明。",
  "No version": "暂无版本",
  "Enabled": "已启用",
  "Recommended": "推荐",
  "Drafts": "草稿",
  "Archived": "已归档",
  "AI analysis of Issues authored in GitHub or GitLab. Each row is the latest revision of one provider Issue; code-review finding aggregates remain separate.": "分析 GitHub 或 GitLab 中创建的 Issue。每行显示一个平台 Issue 的最新版本；代码审核发现项的聚合另行查看。",
  "Issue format rules": "Issue 格式规则",
  "Finding aggregates": "发现项聚合",
  "Provider Issue analysis counts": "代码平台 Issue 分析统计",
  "Queued": "排队中",
  "Acknowledged": "已确认",
  "Completed": "已完成",
  "Failed": "失败",
  "Delivery exhausted": "投递重试已耗尽",
  "Step consumed": "消息已消费",
  "Connection blocked": "连接受阻",
  "View blocked analyses": "查看受阻分析",
  "View tasks needing attention": "查看待处理任务",
  "View recovery tasks": "查看待恢复任务",
  "Provider Issue analysis states": "代码平台 Issue 分析状态",
  "Search Provider Issues": "搜索代码平台 Issue",
  "Search repository, title, author, or Issue number…": "搜索仓库、标题、作者或 Issue 编号…",
  "Search": "搜索",
  "Check Issue event connection": "检查 Issue 事件连接",
  "Open connections": "打开连接设置",
  "Provider Issue triage unavailable": "代码平台 Issue 分析暂不可用",
  "opened by": "创建者",
  "· attempt": "· 尝试",
  "· Issue #": "· Issue #",
  "Close analysis": "关闭分析",
  "Provider reaction feedback": "代码平台表态反馈",
  "Feedback only · never retriggers analysis": "仅记录反馈 · 不会重新触发分析",
  "GitHub reaction sync:": "GitHub 表态同步：",
  "· next": "· 下次",
  "Open Issue in": "打开 Issue，平台：",
  "Configure this repository's format": "配置此仓库的格式",
  "Connection blocked:": "连接受阻：",
  "This analysis retains its queued state and exact Issue revision, but cannot advance while its Git connection is inactive or unverified.": "此分析保留排队状态和准确的 Issue 版本，但 Git 连接未启用或未验证时无法继续。",
  "Open this connection": "打开此连接",
  "This connection is inactive or not verified. Repair it before retrying.": "此连接未启用或未验证。请修复后再重试。",
  "Finish workspace setup before retrying this Issue analysis.": "请先完成工作区设置，再重试此 Issue 分析。",
  "Your workspace role cannot retry this Issue analysis. Ask an authorized reviewer or administrator.": "你的工作区角色不能重试此 Issue 分析。请联系有权限的审核者或管理员。",
  "This retained attempt is not eligible for another retry. Review its revision and retry limit before taking further action.": "此保留的尝试不符合再次重试的条件。请先检查版本和重试限制。",
  "Latest AI analysis": "最新 AI 分析",
  "The latest revision has not produced a final analysis yet.": "最新版本尚未产出最终分析。",
  "Webhook revision evidence": "Webhook 版本证据",
  "Model route snapshot": "模型路由快照",
  "Prompt snapshot": "提示词快照",
  "Issue format snapshot": "Issue 格式快照",
  "Retry required": "需要重试",
  "Requesting…": "请求中…",
  "Request governed Agent task": "申请受治理的 Agent 任务",
  "View repository policy": "查看仓库策略",
  "This Issue snapshot has multiple historical Agent tasks. No further task can be requested for this revision; inspect both tasks, or edit the Issue to create a new revision for new work.": "此 Issue 快照有多个历史 Agent 任务，不能对此版本申请更多任务。请检查这些任务，或编辑 Issue，为新任务创建新版本。",
  "Agent admission status is unavailable in preview or while the control plane is disconnected.": "预览环境或控制服务断开时，Agent 准入状态不可用。",
  "Repository Agent policy is {mode}; enable Manual before requesting work.": "仓库 Agent 策略为{mode}。请求任务前请启用手动模式。",
  "This Issue's original provider installation no longer uniquely owns the repository. Reconnect it before requesting work.": "此 Issue 原有的平台安装不再唯一拥有该仓库。请求任务前请重新连接。",
  "This account cannot request an Agent task for this Issue. Check your workspace role and provider installation.": "此账号不能为该 Issue 申请 Agent 任务。请检查工作区角色和平台安装。",
  "No Provider Issue analyses match these filters.": "没有符合这些筛选条件的代码平台 Issue 分析。",
  "No GitHub or GitLab Issue webhook has been admitted for AI triage yet.": "尚未接收用于 AI 分析的 GitHub 或 GitLab Issue Webhook。",
  "No matching analyses": "没有匹配的分析",
  "No Provider Issues analyzed yet": "尚未分析代码平台 Issue",
  "Provider Issue triage is temporarily unavailable.": "代码平台 Issue 分析暂不可用。",
  "unknown": "未知",
  "After restoring it, an authorized operator must retry this retained delivery.": "恢复后，需由授权操作人员重试此保留的投递。",
  "After verification, check whether this pending delivery advances; this page will show an explicit retry if its message is consumed or exhausted.": "验证后，请检查此待投递任务是否继续；若消息已消费或重试耗尽，此页面将显示重试入口。",
  "Delivery exhausted:": "投递重试已耗尽：",
  "Step consumed:": "消息已消费：",
  "Last error:": "最近错误：",
  "The current Issue step exhausted queue retries. The retained revision can be retried after its gates are ready.": "当前 Issue 步骤已耗尽队列重试。检查条件就绪后，可重试保留的版本。",
  "The current Issue message was consumed without advancing this job. Reconnect if needed, then retry the exact retained snapshot.": "当前 Issue 消息已消费，但任务没有继续。必要时请重新连接，然后重试准确的保留快照。",
  "· awaiting first poll": "· 等待首次轮询",
  "· observed {time}": "· 观测时间 {time}",
  "{count} pending Issue analysis(es) blocked because the Git connection is inactive or unverified. Restore it, then check whether the retained delivery needs an authorized retry.": "{count} 项 Issue 分析因 Git 连接未启用或未验证而受阻。请恢复连接，再检查保留的投递是否需要授权重试。",
  "{count} Issue step(s) exhausted queue retries. Repair the connection, then an authorized operator must retry the retained revision.": "{count} 个 Issue 步骤已耗尽队列重试。请修复连接，再由授权操作人员重试保留的版本。",
  "{count} Issue step(s) were consumed without progress. Restoring a connection cannot replay that message; an authorized operator can retry the exact snapshot once its gates are ready.": "{count} 个 Issue 步骤的消息已消费，但未取得进展。恢复连接无法回放该消息；检查条件就绪后，可由授权操作人员重试准确的快照。",
  "Delivery retries exhausted while the retained job state is {state}": "投递重试已耗尽；保留的任务状态为{state}",
  "Connection is inactive or unverified; retained job state is {state}": "连接未启用或未验证；保留的任务状态为{state}",
  "Current {state} step was consumed without progress; retry is required": "当前{state}步骤的消息已消费但没有进展，需要重试",
  "Analysis detail": "分析详情",
  "manual": "手动",
  "disabled": "已禁用",
  "suggest": "仅建议",
  "retired": "已停用",
  "Repository evidence": "仓库证据",
  "Only active feedback is counted. Deleted reactions remain auditable but no longer affect these measurements.": "仅统计有效反馈。已删除的表态仍可审计，但不再影响这些指标。",
  "immutable snapshot(s) ·": "个不可变快照 ·",
  "high-risk finding(s)": "项高风险发现",
  "No finding feedback evidence yet": "暂无发现项反馈证据",
  "Reviewer dispositions are actor-scoped and auditable; they never rewrite the original AI result.": "审核者的处理决定按操作者记录且可审计，不会改写原始 AI 结果。",
  "Finding results are unavailable": "发现项结果暂不可用",
  "Review evidence": "审核证据",
  "Open": "打开",
  "Resolved": "已解决",
  "Won't fix": "不予修复",
  "No findings match this view": "没有符合此视图的发现项",
  "Recent findings": "最近发现项",
  "The finding disposition could not be updated.": "发现项处理决定未能更新。",
  "The finding disposition could not reach the control plane.": "发现项处理决定未能送达控制服务。",
  "Published findings": "已发布发现项",
  "Feedback events": "反馈事件",
  "Response coverage": "反馈覆盖率",
  "Useful among rated": "已评价项中的有效比例",
  "Reactions on future inline findings will appear here.": "后续行内发现项的表态将显示在此处。",
  "Adjust the view or search filters to inspect other findings.": "调整视图或搜索筛选条件以查看其他发现项。",
  "Finding disposition updated to {state}.": "发现项处理状态已更新为{state}。",
  "{kind} repair evidence": "{kind}修复证据",
  "acceptance": "验收",
  "review": "审核",
  "verification": "验证",
  "This cycle is bound to comment #{comment} by provider user #{actor}. The instruction is checked again before execution and publication.": "此轮绑定代码平台用户 #{actor} 的评论 #{comment}。执行和发布前会再次检查指令。",
  "· {count} feedback cycle(s)": " · {count} 轮反馈",
  "· {count} with unconfirmed publication evidence": " · {count} 项发布证据未确认",
  "Attempt {number}": "第 {number} 次尝试",
  "Open {resource} in {provider}": "在 {provider} 打开{resource}",
  "Waiting for an exact-commit review and independent CI": "等待准确提交的审核与独立 CI",
  "Provider status could not be verified; no acceptance inferred": "无法验证代码平台状态，不能推断已验收",
  "Review admission is blocked; check review policy, installation setup and limits": "审核准入受阻，请检查审核策略、平台安装设置和限额",
  "The provider head changed; this acceptance belongs only to the retained commit": "平台提交已变更；此验收仅对应保留的提交",
  "Draft closed without merge": "草稿已关闭，未合并",
  "Review requires attention or reports blocking findings": "审核需要处理或报告了阻断项",
  "Independent CI observation exhausted retries; restore provider access and retry this review": "独立 CI 状态观测已耗尽重试，请恢复平台访问并重试此审核",
  "The isolated adapter or its coding model is unavailable. No execution attempt was leased and no task budget was consumed. Restore adapter/model readiness, inspect worker health, then create and approve a new plan.": "隔离适配器或编码模型不可用。没有发放执行租约，也没有消耗任务额度。请恢复适配器和模型就绪状态，检查工作进程健康，再创建并批准新计划。",
} as const;

export type WorkflowMessage = keyof typeof workflowCopy;
export type WorkflowMessageValues = Readonly<Record<string, string | number>>;

export function workflowText(language: UiLanguage, source: string, values?: WorkflowMessageValues): string {
  const key = source.trim();
  if (!key) return source;
  const translated = language === "zh-CN" && Object.hasOwn(workflowCopy, key)
    ? workflowCopy[key as WorkflowMessage]
    : key;
  // Replace only authored placeholders, once. Values may contain braces, hashes
  // or '$&' and must never be interpreted as replacement strings or new keys.
  const text = values ? translated.replace(/\{([A-Za-z][A-Za-z0-9_]*)\}/g, (match, name: string) =>
    Object.hasOwn(values, name) ? String(values[name]) : match) : translated;
  return `${source.match(/^\s*/)?.[0] ?? ""}${text}${source.match(/\s*$/)?.[0] ?? ""}`;
}

const statusCopy = {
  reviewing: ["Reviewing", "审核中"],
  resolved: ["Resolved", "已解决"], wont_fix: ["Won’t fix", "不予修复"], unresolved: ["Unresolved", "未解决"],
  acknowledged: ["Acknowledged", "已确认"], retired: ["Retired", "已停用"],
  received: ["Received", "已接收"], plan_ready: ["Plan ready", "计划已就绪"], execution_queued: ["Execution queued", "执行已入队"],
  awaiting_source: ["Awaiting source", "等待来源"], awaiting_plan: ["Awaiting plan", "等待计划"],
  awaiting_approval: ["Awaiting approval", "等待审批"], queued: ["Queued", "排队中"],
  running: ["Running", "执行中"], executing: ["Executing", "执行中"], verifying: ["Verifying", "验证中"],
  completed: ["Completed", "已完成"], succeeded: ["Succeeded", "成功"], failed: ["Failed", "失败"],
  needs_attention: ["Needs attention", "需要处理"], cancelled: ["Cancelled", "已取消"],
  rejected: ["Rejected", "已拒绝"], superseded: ["Superseded", "已被替代"], pending: ["Pending", "待处理"],
  approved: ["Approved", "已批准"], draft: ["Draft", "草稿"], published: ["Published", "已发布"],
  awaiting_acceptance: ["Awaiting acceptance", "等待验收"], accepted: ["Accepted", "已接受"],
  changes_requested: ["Changes requested", "要求修改"], awaiting_checks: ["Awaiting checks", "等待检查"],
  checks_pending: ["Checks pending", "检查待完成"], checks_failed: ["Checks failed", "检查失败"],
  passed: ["Passed", "通过"], low: ["Low", "低"], medium: ["Medium", "中"], high: ["High", "高"], critical: ["Critical", "严重"],
  requires_human: ["Requires human", "需要人工处理"], await_plan_approval: ["Await plan approval", "等待计划批准"],
  in_review: ["In review", "审核中"], active: ["Active", "已生效"], paused: ["Paused", "已暂停"], promoted: ["Promoted", "已提升"],
  rolled_back: ["Rolled back", "已回滚"], expired: ["Expired", "已到期"], revoked: ["Revoked", "已撤销"],
  analyzing: ["Analyzing", "分析中"], preparing: ["Preparing", "准备中"], publishing: ["Publishing", "发布中"],
} as const;

export function workflowStatus(language: UiLanguage, state: string): string {
  const value = Object.hasOwn(statusCopy, state) ? statusCopy[state as keyof typeof statusCopy] : undefined;
  return value ? value[language === "zh-CN" ? 1 : 0] : state.replaceAll("_", " ");
}
