import { Clock3, KeyRound, ShieldCheck, WalletCards } from "lucide-react";

import { EnterpriseSettingsTabs } from "@/components/console/enterprise-settings-tabs";
import { ModelSettingsTabs, type ModelSettingsTab } from "@/components/console/model-settings-tabs";
import { DataFreshness, PageState } from "@/components/console/page-state";
import type { DataSource, ReviewConfigHistory, ReviewConfigView } from "@/lib/control-api";
import { cn } from "@/lib/utils";
import type { ModelScope } from "@/lib/model-scope";

export function ModelRouteGovernanceView({ config, detail, history, org, requestedScope, source, tab }: { config?: ReviewConfigView; detail?: string; history?: ReviewConfigHistory; org: string; requestedScope: ModelScope; source: DataSource; tab: Exclude<ModelSettingsTab, "routes"> }) {
  const scope: ModelScope = config ? { scope_kind: config.requested_scope_kind, scope_ref: config.requested_scope_ref, scope_provider: config.requested_scope_provider ?? requestedScope.scope_provider, scope_api_base_url: config.requested_scope_api_base_url ?? requestedScope.scope_api_base_url } : requestedScope;
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--ls-accent)]">Enterprise control plane</p><h1 className="mt-2 text-[32px] font-semibold tracking-[-0.045em] text-[var(--ls-text)]">Models & BYOK</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--ls-text-secondary)]">Inspect governed route metadata without exposing model credentials or claiming provider health.</p></div><DataFreshness detail={detail} state={source} /></header>
    <EnterpriseSettingsTabs active="models" org={org} />
    <ModelSettingsTabs active={tab} org={org} scope={scope} />
    {!config || (source !== "live" && source !== "demo") ? <Unavailable detail={detail ?? "The model route could not be loaded."} /> : tab === "credentials" ? <Credentials config={config} /> : tab === "budgets" ? <Budgets config={config} /> : <History history={history} source={source} />}
  </div>;
}

function Credentials({ config }: { config: ReviewConfigView }) {
  const content = config.content;
  return <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><article className="rounded-[18px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[12px] bg-[var(--ls-accent-soft)] text-[var(--ls-accent)]"><KeyRound className="size-5" /></span><div><h2 className="text-lg font-semibold text-[var(--ls-text)]">Credential reference</h2><p className="text-xs text-[var(--ls-text-secondary)]">Reference only — no secret value is returned by this control-plane read model.</p></div></div><dl className="mt-6 divide-y divide-[var(--ls-line)] rounded-[14px] border border-[var(--ls-line)]"><Metric label="Provider" value={text(content, "provider") || "deployment"} /><Metric label="Protocol" value={text(content, "protocol") || "deployment"} /><Metric label="Model" value={text(content, "model") || "Not configured"} /><Metric label="Credential reference" mono value={text(content, "credential_ref") || "No external credential reference configured"} /><Metric label="Effective scope" value={scopeName(config)} /></dl></article><Boundary title="Resolution boundary">The runner resolves a configured reference immediately before the review child process starts. The database, audit display, snapshots, and provider report never receive the secret value.</Boundary></section>;
}

function Budgets({ config }: { config: ReviewConfigView }) {
  const content = config.content;
  const tenantScope = config.requested_scope_kind === "tenant";
  return <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><article className="rounded-[18px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[12px] bg-[var(--ls-accent-soft)] text-[var(--ls-accent)]"><WalletCards className="size-5" /></span><div><h2 className="text-lg font-semibold text-[var(--ls-text)]">Admission budgets</h2><p className="text-xs text-[var(--ls-text-secondary)]">Run budgets are snapshotted at admission. Tenant capacity remains owned by the active workspace policy.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><BudgetCard label="Max prompt" value={number(content, "max_prompt_tokens", 8000)} suffix="tokens" /><BudgetCard label="Run budget" value={number(content, "token_budget", 128000)} suffix="tokens" /><BudgetCard label="Subtask timeout" value={number(content, "subtask_timeout_minutes", 5)} suffix="minutes" />{tenantScope ? <BudgetCard label="Tenant concurrency" value={number(content, "max_concurrent_runs", 2)} suffix="runs" /> : <BudgetCard label="Tenant concurrency" value="Workspace" suffix="policy" />}</div><p className="mt-5 text-xs text-[var(--ls-text-tertiary)]">Effective from {scopeName(config)} revision {config.revision} · {config.content_sha256.slice(0, 12)}</p></article><Boundary title="Execution boundary">{tenantScope ? "Concurrency limits active review leases for this tenant; when capacity is full, the durable queue delays the run rather than dropping it. It is not a billing limit." : "Repository routes cannot change tenant concurrency. Switch to Workspace scope to inspect or edit the shared execution capacity."}</Boundary></section>;
}

function History({ history, source }: { history?: ReviewConfigHistory; source: DataSource }) {
  const versions = history?.versions ?? [];
  const emptyDetail = source === "demo" ? "This preview has no retained route history. Its displayed revision is fixture metadata, not persisted provenance." : "This route currently resolves from the built-in deployment default. No persisted workspace or repository revision exists yet.";
  const boundary = source === "demo" ? "This preview does not call the history control plane. Configuration content, credential references, secrets, and provider responses remain outside this fixture." : "Only revision provenance is listed here. Configuration content, credential references, secrets, and any provider response stay outside the history read model.";
  return <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><article className="rounded-[18px] border border-[var(--ls-line)] bg-[var(--ls-surface)] p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[12px] bg-[var(--ls-accent-soft)] text-[var(--ls-accent)]"><Clock3 className="size-5" /></span><div><h2 className="text-lg font-semibold text-[var(--ls-text)]">Immutable route history</h2><p className="text-xs text-[var(--ls-text-secondary)]">Persisted revisions are newest first. Existing review runs remain pinned to their admission snapshot.</p></div></div>{versions.length ? <ol className="mt-6 space-y-2">{versions.map((version) => <li className="grid gap-2 rounded-[12px] border border-[var(--ls-line)] bg-[var(--ls-surface-muted)] p-4 sm:grid-cols-[90px_minmax(0,1fr)_auto] sm:items-center" key={version.revision}><span className="font-mono text-sm font-semibold text-[var(--ls-text)]">v{version.revision}</span><span className="min-w-0"><span className="block truncate font-mono text-xs text-[var(--ls-text-secondary)]">{version.content_sha256}</span><span className="mt-1 block text-[11px] text-[var(--ls-text-tertiary)]">by {version.created_by}</span></span><time className="text-xs text-[var(--ls-text-secondary)]" dateTime={version.created_at}>{formatDate(version.created_at)}</time></li>)}</ol> : <p className="mt-6 rounded-[12px] border border-dashed border-[var(--ls-line-strong)] p-4 text-sm text-[var(--ls-text-secondary)]">{emptyDetail}</p>}</article><Boundary title="History boundary">{boundary}</Boundary></section>;
}

function Boundary({ children, title }: { children: React.ReactNode; title: string }) { return <aside className="rounded-[18px] border border-amber-500/25 bg-amber-500/[0.06] p-5"><div className="flex items-center gap-2 text-sm font-semibold text-[var(--ls-warning-text)]"><ShieldCheck className="size-4" />{title}</div><p className="mt-2 text-xs leading-5 text-[var(--ls-text-secondary)]">{children}</p></aside>; }
function BudgetCard({ label, suffix, value }: { label: string; suffix: string; value: number | string }) { return <div className="rounded-[14px] border border-[var(--ls-line)] bg-[var(--ls-surface-muted)] p-4"><p className="text-xs text-[var(--ls-text-secondary)]">{label}</p><p className="mt-2 text-xl font-semibold tracking-[-0.03em] text-[var(--ls-text)]">{value.toLocaleString()} <span className="text-xs font-medium text-[var(--ls-text-tertiary)]">{suffix}</span></p></div>; }
function Metric({ label, mono, value }: { label: string; mono?: boolean; value: string }) { return <div className="grid gap-1 px-4 py-3 sm:grid-cols-[150px_minmax(0,1fr)] sm:items-center"><dt className="text-xs text-[var(--ls-text-secondary)]">{label}</dt><dd className={cn("min-w-0 break-all text-sm text-[var(--ls-text)]", mono && "font-mono text-xs")}>{value}</dd></div>; }
function Unavailable({ detail }: { detail: string }) { return <PageState className="min-h-72" detail={detail} kind="unavailable" title="Model control plane unavailable" />; }
function text(content: Record<string, unknown>, key: string) { const value = content[key]; return typeof value === "string" ? value : ""; }
function number(content: Record<string, unknown>, key: string, fallback: number) { const value = content[key]; return typeof value === "number" ? value : fallback; }
function scopeName(config: ReviewConfigView) { return config.requested_scope_kind === "repository" ? [config.requested_scope_ref || "Repository", config.requested_scope_provider, config.requested_scope_api_base_url].filter(Boolean).join(" · ") : "Workspace"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
